# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainv3.ui'
#
# Created: Thu Mar  7 22:11:46 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1024, 768)
        Dialog.setAutoFillBackground(False)
        self.startButton = QtGui.QPushButton(Dialog)
        self.startButton.setEnabled(True)
        self.startButton.setGeometry(QtCore.QRect(10, 710, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.startButton.setFont(font)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.restartButton = QtGui.QPushButton(Dialog)
        self.restartButton.setEnabled(False)
        self.restartButton.setGeometry(QtCore.QRect(160, 710, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.restartButton.setFont(font)
        self.restartButton.setObjectName(_fromUtf8("restartButton"))
        self.batchModeButton = QtGui.QPushButton(Dialog)
        self.batchModeButton.setGeometry(QtCore.QRect(780, 710, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.batchModeButton.setFont(font)
        self.batchModeButton.setObjectName(_fromUtf8("batchModeButton"))
        self.mainTabWidget = QtGui.QTabWidget(Dialog)
        self.mainTabWidget.setGeometry(QtCore.QRect(10, 10, 1001, 691))
        self.mainTabWidget.setObjectName(_fromUtf8("mainTabWidget"))
        self.inputTab = QtGui.QWidget()
        self.inputTab.setObjectName(_fromUtf8("inputTab"))
        self.imageGroup = QtGui.QGroupBox(self.inputTab)
        self.imageGroup.setGeometry(QtCore.QRect(10, 10, 981, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imageGroup.setFont(font)
        self.imageGroup.setFlat(False)
        self.imageGroup.setCheckable(False)
        self.imageGroup.setObjectName(_fromUtf8("imageGroup"))
        self.imageRGB = QtGui.QGraphicsView(self.imageGroup)
        self.imageRGB.setGeometry(QtCore.QRect(30, 30, 192, 192))
        self.imageRGB.setObjectName(_fromUtf8("imageRGB"))
        self.imageRed = QtGui.QGraphicsView(self.imageGroup)
        self.imageRed.setGeometry(QtCore.QRect(270, 30, 192, 192))
        self.imageRed.setObjectName(_fromUtf8("imageRed"))
        self.imageGreen = QtGui.QGraphicsView(self.imageGroup)
        self.imageGreen.setGeometry(QtCore.QRect(510, 30, 192, 192))
        self.imageGreen.setObjectName(_fromUtf8("imageGreen"))
        self.imageBlue = QtGui.QGraphicsView(self.imageGroup)
        self.imageBlue.setGeometry(QtCore.QRect(750, 30, 192, 192))
        self.imageBlue.setObjectName(_fromUtf8("imageBlue"))
        self.labelRGB = QtGui.QLabel(self.imageGroup)
        self.labelRGB.setGeometry(QtCore.QRect(80, 220, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelRGB.setFont(font)
        self.labelRGB.setObjectName(_fromUtf8("labelRGB"))
        self.labelRed = QtGui.QLabel(self.imageGroup)
        self.labelRed.setGeometry(QtCore.QRect(350, 220, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelRed.setFont(font)
        self.labelRed.setObjectName(_fromUtf8("labelRed"))
        self.labelGreen = QtGui.QLabel(self.imageGroup)
        self.labelGreen.setGeometry(QtCore.QRect(580, 220, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelGreen.setFont(font)
        self.labelGreen.setObjectName(_fromUtf8("labelGreen"))
        self.labelBlue = QtGui.QLabel(self.imageGroup)
        self.labelBlue.setGeometry(QtCore.QRect(830, 220, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelBlue.setFont(font)
        self.labelBlue.setObjectName(_fromUtf8("labelBlue"))
        self.imageSettingsGroup = QtGui.QGroupBox(self.inputTab)
        self.imageSettingsGroup.setGeometry(QtCore.QRect(10, 290, 351, 191))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imageSettingsGroup.setFont(font)
        self.imageSettingsGroup.setObjectName(_fromUtf8("imageSettingsGroup"))
        self.imageSettingsTabWidget = QtGui.QTabWidget(self.imageSettingsGroup)
        self.imageSettingsTabWidget.setGeometry(QtCore.QRect(0, 20, 341, 161))
        self.imageSettingsTabWidget.setObjectName(_fromUtf8("imageSettingsTabWidget"))
        self.loadThreeTab = QtGui.QWidget()
        self.loadThreeTab.setObjectName(_fromUtf8("loadThreeTab"))
        self.loadImageRed = QtGui.QPushButton(self.loadThreeTab)
        self.loadImageRed.setGeometry(QtCore.QRect(10, 10, 211, 31))
        self.loadImageRed.setObjectName(_fromUtf8("loadImageRed"))
        self.loadImageGreen = QtGui.QPushButton(self.loadThreeTab)
        self.loadImageGreen.setGeometry(QtCore.QRect(10, 50, 211, 31))
        self.loadImageGreen.setObjectName(_fromUtf8("loadImageGreen"))
        self.loadImageBlue = QtGui.QPushButton(self.loadThreeTab)
        self.loadImageBlue.setGeometry(QtCore.QRect(10, 90, 211, 31))
        self.loadImageBlue.setObjectName(_fromUtf8("loadImageBlue"))
        self.redChannelFile = QtGui.QLabel(self.loadThreeTab)
        self.redChannelFile.setGeometry(QtCore.QRect(230, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.redChannelFile.setFont(font)
        self.redChannelFile.setFrameShape(QtGui.QFrame.Box)
        self.redChannelFile.setFrameShadow(QtGui.QFrame.Sunken)
        self.redChannelFile.setAlignment(QtCore.Qt.AlignCenter)
        self.redChannelFile.setObjectName(_fromUtf8("redChannelFile"))
        self.greenChannelFile = QtGui.QLabel(self.loadThreeTab)
        self.greenChannelFile.setGeometry(QtCore.QRect(230, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.greenChannelFile.setFont(font)
        self.greenChannelFile.setFrameShape(QtGui.QFrame.Box)
        self.greenChannelFile.setFrameShadow(QtGui.QFrame.Sunken)
        self.greenChannelFile.setAlignment(QtCore.Qt.AlignCenter)
        self.greenChannelFile.setObjectName(_fromUtf8("greenChannelFile"))
        self.blueChannelFile = QtGui.QLabel(self.loadThreeTab)
        self.blueChannelFile.setGeometry(QtCore.QRect(230, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.blueChannelFile.setFont(font)
        self.blueChannelFile.setFrameShape(QtGui.QFrame.Box)
        self.blueChannelFile.setFrameShadow(QtGui.QFrame.Sunken)
        self.blueChannelFile.setAlignment(QtCore.Qt.AlignCenter)
        self.blueChannelFile.setObjectName(_fromUtf8("blueChannelFile"))
        self.imageSettingsTabWidget.addTab(self.loadThreeTab, _fromUtf8(""))
        self.loadSingleTab = QtGui.QWidget()
        self.loadSingleTab.setObjectName(_fromUtf8("loadSingleTab"))
        self.loadImageRGB = QtGui.QPushButton(self.loadSingleTab)
        self.loadImageRGB.setGeometry(QtCore.QRect(50, 10, 221, 31))
        self.loadImageRGB.setObjectName(_fromUtf8("loadImageRGB"))
        self.rgbFile = QtGui.QLabel(self.loadSingleTab)
        self.rgbFile.setGeometry(QtCore.QRect(50, 70, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rgbFile.setFont(font)
        self.rgbFile.setFrameShape(QtGui.QFrame.Box)
        self.rgbFile.setFrameShadow(QtGui.QFrame.Sunken)
        self.rgbFile.setAlignment(QtCore.Qt.AlignCenter)
        self.rgbFile.setObjectName(_fromUtf8("rgbFile"))
        self.imageSettingsTabWidget.addTab(self.loadSingleTab, _fromUtf8(""))
        self.attributesGroup = QtGui.QGroupBox(self.inputTab)
        self.attributesGroup.setGeometry(QtCore.QRect(10, 500, 351, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.attributesGroup.setFont(font)
        self.attributesGroup.setObjectName(_fromUtf8("attributesGroup"))
        self.imageSizeLabel = QtGui.QLabel(self.attributesGroup)
        self.imageSizeLabel.setGeometry(QtCore.QRect(10, 50, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.imageSizeLabel.setFont(font)
        self.imageSizeLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.imageSizeLabel.setObjectName(_fromUtf8("imageSizeLabel"))
        self.imageSizeText = QtGui.QLabel(self.attributesGroup)
        self.imageSizeText.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.imageSizeText.setFrameShape(QtGui.QFrame.Box)
        self.imageSizeText.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageSizeText.setText(_fromUtf8(""))
        self.imageSizeText.setObjectName(_fromUtf8("imageSizeText"))
        self.avgIntensityLabel = QtGui.QLabel(self.attributesGroup)
        self.avgIntensityLabel.setGeometry(QtCore.QRect(180, 25, 131, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.avgIntensityLabel.setFont(font)
        self.avgIntensityLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.avgIntensityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avgIntensityLabel.setWordWrap(True)
        self.avgIntensityLabel.setObjectName(_fromUtf8("avgIntensityLabel"))
        self.redIntensityLabel = QtGui.QLabel(self.attributesGroup)
        self.redIntensityLabel.setGeometry(QtCore.QRect(170, 70, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.redIntensityLabel.setFont(font)
        self.redIntensityLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.redIntensityLabel.setObjectName(_fromUtf8("redIntensityLabel"))
        self.redIntensityLabel_2 = QtGui.QLabel(self.attributesGroup)
        self.redIntensityLabel_2.setGeometry(QtCore.QRect(160, 90, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.redIntensityLabel_2.setFont(font)
        self.redIntensityLabel_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.redIntensityLabel_2.setObjectName(_fromUtf8("redIntensityLabel_2"))
        self.redIntensityLabel_3 = QtGui.QLabel(self.attributesGroup)
        self.redIntensityLabel_3.setGeometry(QtCore.QRect(170, 110, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.redIntensityLabel_3.setFont(font)
        self.redIntensityLabel_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.redIntensityLabel_3.setObjectName(_fromUtf8("redIntensityLabel_3"))
        self.redIntensityText = QtGui.QLabel(self.attributesGroup)
        self.redIntensityText.setGeometry(QtCore.QRect(220, 70, 91, 21))
        self.redIntensityText.setFrameShape(QtGui.QFrame.Box)
        self.redIntensityText.setFrameShadow(QtGui.QFrame.Sunken)
        self.redIntensityText.setText(_fromUtf8(""))
        self.redIntensityText.setObjectName(_fromUtf8("redIntensityText"))
        self.greenIntensityText = QtGui.QLabel(self.attributesGroup)
        self.greenIntensityText.setGeometry(QtCore.QRect(220, 90, 91, 21))
        self.greenIntensityText.setFrameShape(QtGui.QFrame.Box)
        self.greenIntensityText.setFrameShadow(QtGui.QFrame.Sunken)
        self.greenIntensityText.setText(_fromUtf8(""))
        self.greenIntensityText.setObjectName(_fromUtf8("greenIntensityText"))
        self.blueIntensityText = QtGui.QLabel(self.attributesGroup)
        self.blueIntensityText.setGeometry(QtCore.QRect(220, 110, 91, 21))
        self.blueIntensityText.setFrameShape(QtGui.QFrame.Box)
        self.blueIntensityText.setFrameShadow(QtGui.QFrame.Sunken)
        self.blueIntensityText.setText(_fromUtf8(""))
        self.blueIntensityText.setObjectName(_fromUtf8("blueIntensityText"))
        self.line = QtGui.QFrame(self.attributesGroup)
        self.line.setGeometry(QtCore.QRect(110, 20, 20, 121))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.correlationSettingsGroup = QtGui.QGroupBox(self.inputTab)
        self.correlationSettingsGroup.setGeometry(QtCore.QRect(370, 280, 621, 321))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.correlationSettingsGroup.setFont(font)
        self.correlationSettingsGroup.setObjectName(_fromUtf8("correlationSettingsGroup"))
        self.correlationTabWidget = QtGui.QTabWidget(self.correlationSettingsGroup)
        self.correlationTabWidget.setGeometry(QtCore.QRect(10, 30, 481, 281))
        self.correlationTabWidget.setObjectName(_fromUtf8("correlationTabWidget"))
        self.autoCorrelationTab = QtGui.QWidget()
        self.autoCorrelationTab.setObjectName(_fromUtf8("autoCorrelationTab"))
        self.autoChannelsGroup = QtGui.QGroupBox(self.autoCorrelationTab)
        self.autoChannelsGroup.setGeometry(QtCore.QRect(10, 10, 121, 231))
        self.autoChannelsGroup.setObjectName(_fromUtf8("autoChannelsGroup"))
        self.redCheckbox = QtGui.QCheckBox(self.autoChannelsGroup)
        self.redCheckbox.setGeometry(QtCore.QRect(20, 50, 70, 17))
        self.redCheckbox.setChecked(True)
        self.redCheckbox.setObjectName(_fromUtf8("redCheckbox"))
        self.greenCheckbox = QtGui.QCheckBox(self.autoChannelsGroup)
        self.greenCheckbox.setGeometry(QtCore.QRect(20, 110, 70, 17))
        self.greenCheckbox.setChecked(True)
        self.greenCheckbox.setObjectName(_fromUtf8("greenCheckbox"))
        self.blueCheckbox = QtGui.QCheckBox(self.autoChannelsGroup)
        self.blueCheckbox.setGeometry(QtCore.QRect(20, 170, 70, 17))
        self.blueCheckbox.setChecked(True)
        self.blueCheckbox.setObjectName(_fromUtf8("blueCheckbox"))
        self.autoGroup = QtGui.QGroupBox(self.autoCorrelationTab)
        self.autoGroup.setGeometry(QtCore.QRect(140, 10, 231, 231))
        self.autoGroup.setFlat(False)
        self.autoGroup.setCheckable(False)
        self.autoGroup.setObjectName(_fromUtf8("autoGroup"))
        self.autoRange = QtGui.QLabel(self.autoGroup)
        self.autoRange.setGeometry(QtCore.QRect(-10, 40, 91, 31))
        self.autoRange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.autoRange.setObjectName(_fromUtf8("autoRange"))
        self.autoG0 = QtGui.QLabel(self.autoGroup)
        self.autoG0.setGeometry(QtCore.QRect(-10, 90, 91, 31))
        self.autoG0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.autoG0.setObjectName(_fromUtf8("autoG0"))
        self.autoW = QtGui.QLabel(self.autoGroup)
        self.autoW.setGeometry(QtCore.QRect(-10, 140, 91, 31))
        self.autoW.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.autoW.setObjectName(_fromUtf8("autoW"))
        self.autoGinf = QtGui.QLabel(self.autoGroup)
        self.autoGinf.setGeometry(QtCore.QRect(-10, 190, 91, 31))
        self.autoGinf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.autoGinf.setObjectName(_fromUtf8("autoGinf"))
        self.autoRangeTextbox = QtGui.QLineEdit(self.autoGroup)
        self.autoRangeTextbox.setGeometry(QtCore.QRect(110, 40, 101, 31))
        self.autoRangeTextbox.setObjectName(_fromUtf8("autoRangeTextbox"))
        self.autoG0Textbox = QtGui.QLineEdit(self.autoGroup)
        self.autoG0Textbox.setGeometry(QtCore.QRect(110, 90, 101, 31))
        self.autoG0Textbox.setObjectName(_fromUtf8("autoG0Textbox"))
        self.autoWTextbox = QtGui.QLineEdit(self.autoGroup)
        self.autoWTextbox.setGeometry(QtCore.QRect(110, 140, 101, 31))
        self.autoWTextbox.setObjectName(_fromUtf8("autoWTextbox"))
        self.autoGinfTextbox = QtGui.QLineEdit(self.autoGroup)
        self.autoGinfTextbox.setGeometry(QtCore.QRect(110, 190, 101, 31))
        self.autoGinfTextbox.setObjectName(_fromUtf8("autoGinfTextbox"))
        self.correlationTabWidget.addTab(self.autoCorrelationTab, _fromUtf8(""))
        self.crossCorrelationTab = QtGui.QWidget()
        self.crossCorrelationTab.setObjectName(_fromUtf8("crossCorrelationTab"))
        self.crossGroup = QtGui.QGroupBox(self.crossCorrelationTab)
        self.crossGroup.setGeometry(QtCore.QRect(140, 10, 231, 231))
        self.crossGroup.setFlat(False)
        self.crossGroup.setCheckable(False)
        self.crossGroup.setObjectName(_fromUtf8("crossGroup"))
        self.crossRange = QtGui.QLabel(self.crossGroup)
        self.crossRange.setGeometry(QtCore.QRect(-10, 40, 91, 31))
        self.crossRange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.crossRange.setObjectName(_fromUtf8("crossRange"))
        self.crossG0 = QtGui.QLabel(self.crossGroup)
        self.crossG0.setGeometry(QtCore.QRect(-10, 90, 91, 31))
        self.crossG0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.crossG0.setObjectName(_fromUtf8("crossG0"))
        self.crossW = QtGui.QLabel(self.crossGroup)
        self.crossW.setGeometry(QtCore.QRect(-10, 140, 91, 31))
        self.crossW.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.crossW.setObjectName(_fromUtf8("crossW"))
        self.crossGinf = QtGui.QLabel(self.crossGroup)
        self.crossGinf.setGeometry(QtCore.QRect(-10, 190, 91, 31))
        self.crossGinf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.crossGinf.setObjectName(_fromUtf8("crossGinf"))
        self.crossRangeTextbox = QtGui.QLineEdit(self.crossGroup)
        self.crossRangeTextbox.setGeometry(QtCore.QRect(110, 40, 101, 31))
        self.crossRangeTextbox.setObjectName(_fromUtf8("crossRangeTextbox"))
        self.crossG0Textbox = QtGui.QLineEdit(self.crossGroup)
        self.crossG0Textbox.setGeometry(QtCore.QRect(110, 90, 101, 31))
        self.crossG0Textbox.setObjectName(_fromUtf8("crossG0Textbox"))
        self.crossWTextbox = QtGui.QLineEdit(self.crossGroup)
        self.crossWTextbox.setGeometry(QtCore.QRect(110, 140, 101, 31))
        self.crossWTextbox.setObjectName(_fromUtf8("crossWTextbox"))
        self.crossGinfTextbox = QtGui.QLineEdit(self.crossGroup)
        self.crossGinfTextbox.setGeometry(QtCore.QRect(110, 190, 101, 31))
        self.crossGinfTextbox.setObjectName(_fromUtf8("crossGinfTextbox"))
        self.crossChannelsGroup = QtGui.QGroupBox(self.crossCorrelationTab)
        self.crossChannelsGroup.setGeometry(QtCore.QRect(10, 10, 121, 231))
        self.crossChannelsGroup.setObjectName(_fromUtf8("crossChannelsGroup"))
        self.redGreenCheckbox = QtGui.QCheckBox(self.crossChannelsGroup)
        self.redGreenCheckbox.setGeometry(QtCore.QRect(20, 50, 111, 17))
        self.redGreenCheckbox.setChecked(True)
        self.redGreenCheckbox.setObjectName(_fromUtf8("redGreenCheckbox"))
        self.redBlueCheckbox = QtGui.QCheckBox(self.crossChannelsGroup)
        self.redBlueCheckbox.setGeometry(QtCore.QRect(20, 110, 91, 17))
        self.redBlueCheckbox.setChecked(True)
        self.redBlueCheckbox.setObjectName(_fromUtf8("redBlueCheckbox"))
        self.greenBlueCheckbox = QtGui.QCheckBox(self.crossChannelsGroup)
        self.greenBlueCheckbox.setGeometry(QtCore.QRect(20, 170, 111, 17))
        self.greenBlueCheckbox.setChecked(True)
        self.greenBlueCheckbox.setObjectName(_fromUtf8("greenBlueCheckbox"))
        self.correlationTabWidget.addTab(self.crossCorrelationTab, _fromUtf8(""))
        self.tripleCorrelationTab = QtGui.QWidget()
        self.tripleCorrelationTab.setObjectName(_fromUtf8("tripleCorrelationTab"))
        self.tripleGroup = QtGui.QGroupBox(self.tripleCorrelationTab)
        self.tripleGroup.setGeometry(QtCore.QRect(130, 10, 241, 231))
        self.tripleGroup.setFlat(False)
        self.tripleGroup.setCheckable(False)
        self.tripleGroup.setObjectName(_fromUtf8("tripleGroup"))
        self.tripleRange = QtGui.QLabel(self.tripleGroup)
        self.tripleRange.setGeometry(QtCore.QRect(0, 40, 91, 31))
        self.tripleRange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tripleRange.setObjectName(_fromUtf8("tripleRange"))
        self.tripleG0 = QtGui.QLabel(self.tripleGroup)
        self.tripleG0.setGeometry(QtCore.QRect(0, 90, 91, 31))
        self.tripleG0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tripleG0.setObjectName(_fromUtf8("tripleG0"))
        self.tripleW = QtGui.QLabel(self.tripleGroup)
        self.tripleW.setGeometry(QtCore.QRect(0, 140, 91, 31))
        self.tripleW.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tripleW.setObjectName(_fromUtf8("tripleW"))
        self.tripleGinf = QtGui.QLabel(self.tripleGroup)
        self.tripleGinf.setGeometry(QtCore.QRect(0, 190, 91, 31))
        self.tripleGinf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tripleGinf.setObjectName(_fromUtf8("tripleGinf"))
        self.tripleRangeTextbox = QtGui.QLineEdit(self.tripleGroup)
        self.tripleRangeTextbox.setGeometry(QtCore.QRect(120, 40, 101, 31))
        self.tripleRangeTextbox.setObjectName(_fromUtf8("tripleRangeTextbox"))
        self.tripleG0Textbox = QtGui.QLineEdit(self.tripleGroup)
        self.tripleG0Textbox.setGeometry(QtCore.QRect(120, 90, 101, 31))
        self.tripleG0Textbox.setObjectName(_fromUtf8("tripleG0Textbox"))
        self.tripleWTextbox = QtGui.QLineEdit(self.tripleGroup)
        self.tripleWTextbox.setGeometry(QtCore.QRect(120, 140, 101, 31))
        self.tripleWTextbox.setObjectName(_fromUtf8("tripleWTextbox"))
        self.tripleGinfTextbox = QtGui.QLineEdit(self.tripleGroup)
        self.tripleGinfTextbox.setGeometry(QtCore.QRect(120, 190, 101, 31))
        self.tripleGinfTextbox.setObjectName(_fromUtf8("tripleGinfTextbox"))
        self.correlationTabWidget.addTab(self.tripleCorrelationTab, _fromUtf8(""))
        self.allCorrelationsTab = QtGui.QWidget()
        self.allCorrelationsTab.setObjectName(_fromUtf8("allCorrelationsTab"))
        self.allTripleGroup = QtGui.QGroupBox(self.allCorrelationsTab)
        self.allTripleGroup.setGeometry(QtCore.QRect(220, 20, 231, 221))
        self.allTripleGroup.setFlat(False)
        self.allTripleGroup.setCheckable(False)
        self.allTripleGroup.setObjectName(_fromUtf8("allTripleGroup"))
        self.allTripleRange = QtGui.QLabel(self.allTripleGroup)
        self.allTripleRange.setGeometry(QtCore.QRect(30, 50, 61, 31))
        self.allTripleRange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allTripleRange.setObjectName(_fromUtf8("allTripleRange"))
        self.allTripleG0 = QtGui.QLabel(self.allTripleGroup)
        self.allTripleG0.setGeometry(QtCore.QRect(30, 90, 61, 31))
        self.allTripleG0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allTripleG0.setObjectName(_fromUtf8("allTripleG0"))
        self.allTripleW = QtGui.QLabel(self.allTripleGroup)
        self.allTripleW.setGeometry(QtCore.QRect(20, 130, 71, 31))
        self.allTripleW.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allTripleW.setObjectName(_fromUtf8("allTripleW"))
        self.allTripleGinf = QtGui.QLabel(self.allTripleGroup)
        self.allTripleGinf.setGeometry(QtCore.QRect(20, 170, 71, 31))
        self.allTripleGinf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allTripleGinf.setObjectName(_fromUtf8("allTripleGinf"))
        self.allTripleRangeTextbox = QtGui.QLineEdit(self.allTripleGroup)
        self.allTripleRangeTextbox.setGeometry(QtCore.QRect(120, 50, 101, 31))
        self.allTripleRangeTextbox.setObjectName(_fromUtf8("allTripleRangeTextbox"))
        self.allTripleG0Textbox = QtGui.QLineEdit(self.allTripleGroup)
        self.allTripleG0Textbox.setGeometry(QtCore.QRect(120, 90, 101, 31))
        self.allTripleG0Textbox.setObjectName(_fromUtf8("allTripleG0Textbox"))
        self.allTripleWTextbox = QtGui.QLineEdit(self.allTripleGroup)
        self.allTripleWTextbox.setGeometry(QtCore.QRect(120, 130, 101, 31))
        self.allTripleWTextbox.setObjectName(_fromUtf8("allTripleWTextbox"))
        self.allTripleGinfTextbox = QtGui.QLineEdit(self.allTripleGroup)
        self.allTripleGinfTextbox.setGeometry(QtCore.QRect(120, 170, 101, 31))
        self.allTripleGinfTextbox.setObjectName(_fromUtf8("allTripleGinfTextbox"))
        self.allAutoCrossGroup = QtGui.QGroupBox(self.allCorrelationsTab)
        self.allAutoCrossGroup.setGeometry(QtCore.QRect(10, 20, 201, 221))
        self.allAutoCrossGroup.setFlat(False)
        self.allAutoCrossGroup.setCheckable(False)
        self.allAutoCrossGroup.setObjectName(_fromUtf8("allAutoCrossGroup"))
        self.allAutoCrossRange = QtGui.QLabel(self.allAutoCrossGroup)
        self.allAutoCrossRange.setGeometry(QtCore.QRect(10, 50, 51, 31))
        self.allAutoCrossRange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allAutoCrossRange.setObjectName(_fromUtf8("allAutoCrossRange"))
        self.allAutoCrossG0 = QtGui.QLabel(self.allAutoCrossGroup)
        self.allAutoCrossG0.setGeometry(QtCore.QRect(10, 90, 51, 31))
        self.allAutoCrossG0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allAutoCrossG0.setObjectName(_fromUtf8("allAutoCrossG0"))
        self.allAutoCrossW = QtGui.QLabel(self.allAutoCrossGroup)
        self.allAutoCrossW.setGeometry(QtCore.QRect(10, 130, 51, 31))
        self.allAutoCrossW.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allAutoCrossW.setObjectName(_fromUtf8("allAutoCrossW"))
        self.allAutoCrossGinf = QtGui.QLabel(self.allAutoCrossGroup)
        self.allAutoCrossGinf.setGeometry(QtCore.QRect(10, 170, 51, 31))
        self.allAutoCrossGinf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allAutoCrossGinf.setObjectName(_fromUtf8("allAutoCrossGinf"))
        self.allAutoCrossRange_2 = QtGui.QLineEdit(self.allAutoCrossGroup)
        self.allAutoCrossRange_2.setGeometry(QtCore.QRect(90, 50, 101, 31))
        self.allAutoCrossRange_2.setObjectName(_fromUtf8("allAutoCrossRange_2"))
        self.allAutoCrossG0Textbox = QtGui.QLineEdit(self.allAutoCrossGroup)
        self.allAutoCrossG0Textbox.setGeometry(QtCore.QRect(90, 90, 101, 31))
        self.allAutoCrossG0Textbox.setObjectName(_fromUtf8("allAutoCrossG0Textbox"))
        self.allAutoCrossWTextbox = QtGui.QLineEdit(self.allAutoCrossGroup)
        self.allAutoCrossWTextbox.setGeometry(QtCore.QRect(90, 130, 101, 31))
        self.allAutoCrossWTextbox.setObjectName(_fromUtf8("allAutoCrossWTextbox"))
        self.allAutoCrossGinfTextbox = QtGui.QLineEdit(self.allAutoCrossGroup)
        self.allAutoCrossGinfTextbox.setGeometry(QtCore.QRect(90, 170, 101, 31))
        self.allAutoCrossGinfTextbox.setObjectName(_fromUtf8("allAutoCrossGinfTextbox"))
        self.correlationTabWidget.addTab(self.allCorrelationsTab, _fromUtf8(""))
        self.frame = QtGui.QFrame(self.correlationSettingsGroup)
        self.frame.setGeometry(QtCore.QRect(500, 30, 111, 281))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.sampleResolutionLabel = QtGui.QLabel(self.frame)
        self.sampleResolutionLabel.setGeometry(QtCore.QRect(10, 60, 91, 41))
        self.sampleResolutionLabel.setWordWrap(True)
        self.sampleResolutionLabel.setObjectName(_fromUtf8("sampleResolutionLabel"))
        self.resolution32 = QtGui.QRadioButton(self.frame)
        self.resolution32.setGeometry(QtCore.QRect(20, 120, 82, 17))
        self.resolution32.setObjectName(_fromUtf8("resolution32"))
        self.resolution48 = QtGui.QRadioButton(self.frame)
        self.resolution48.setGeometry(QtCore.QRect(20, 180, 82, 17))
        self.resolution48.setObjectName(_fromUtf8("resolution48"))
        self.resolution64 = QtGui.QRadioButton(self.frame)
        self.resolution64.setGeometry(QtCore.QRect(20, 240, 82, 17))
        self.resolution64.setObjectName(_fromUtf8("resolution64"))
        self.label = QtGui.QLabel(self.inputTab)
        self.label.setGeometry(QtCore.QRect(370, 612, 621, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.WinPanel)
        self.label.setFrameShadow(QtGui.QFrame.Sunken)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.mainTabWidget.addTab(self.inputTab, _fromUtf8(""))
        self.outputTab = QtGui.QWidget()
        self.outputTab.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.outputTab.setObjectName(_fromUtf8("outputTab"))
        self.outputCorrelationTabWidget = QtGui.QTabWidget(self.outputTab)
        self.outputCorrelationTabWidget.setGeometry(QtCore.QRect(10, 10, 971, 641))
        self.outputCorrelationTabWidget.setObjectName(_fromUtf8("outputCorrelationTabWidget"))
        self.autoOutputTab = QtGui.QWidget()
        self.autoOutputTab.setObjectName(_fromUtf8("autoOutputTab"))
        self.imageAutoRed = QtGui.QGraphicsView(self.autoOutputTab)
        self.imageAutoRed.setGeometry(QtCore.QRect(10, 130, 311, 301))
        self.imageAutoRed.setObjectName(_fromUtf8("imageAutoRed"))
        self.labelOutputRed = QtGui.QLabel(self.autoOutputTab)
        self.labelOutputRed.setGeometry(QtCore.QRect(140, 430, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputRed.setFont(font)
        self.labelOutputRed.setObjectName(_fromUtf8("labelOutputRed"))
        self.imageAutoGreen = QtGui.QGraphicsView(self.autoOutputTab)
        self.imageAutoGreen.setGeometry(QtCore.QRect(330, 130, 311, 301))
        self.imageAutoGreen.setObjectName(_fromUtf8("imageAutoGreen"))
        self.imageAutoBlue = QtGui.QGraphicsView(self.autoOutputTab)
        self.imageAutoBlue.setGeometry(QtCore.QRect(650, 130, 311, 301))
        self.imageAutoBlue.setObjectName(_fromUtf8("imageAutoBlue"))
        self.labelOutputGreen = QtGui.QLabel(self.autoOutputTab)
        self.labelOutputGreen.setGeometry(QtCore.QRect(460, 430, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputGreen.setFont(font)
        self.labelOutputGreen.setObjectName(_fromUtf8("labelOutputGreen"))
        self.labelOutputBlue = QtGui.QLabel(self.autoOutputTab)
        self.labelOutputBlue.setGeometry(QtCore.QRect(780, 430, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputBlue.setFont(font)
        self.labelOutputBlue.setObjectName(_fromUtf8("labelOutputBlue"))
        self.labelAutoResNorm = QtGui.QLabel(self.autoOutputTab)
        self.labelAutoResNorm.setGeometry(QtCore.QRect(380, 500, 91, 31))
        self.labelAutoResNorm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAutoResNorm.setObjectName(_fromUtf8("labelAutoResNorm"))
        self.autoResNormValue = QtGui.QLabel(self.autoOutputTab)
        self.autoResNormValue.setGeometry(QtCore.QRect(480, 500, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.autoResNormValue.setFont(font)
        self.autoResNormValue.setFrameShape(QtGui.QFrame.Box)
        self.autoResNormValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.autoResNormValue.setText(_fromUtf8(""))
        self.autoResNormValue.setAlignment(QtCore.Qt.AlignCenter)
        self.autoResNormValue.setObjectName(_fromUtf8("autoResNormValue"))
        self.outputCorrelationTabWidget.addTab(self.autoOutputTab, _fromUtf8(""))
        self.crossOutputTab = QtGui.QWidget()
        self.crossOutputTab.setObjectName(_fromUtf8("crossOutputTab"))
        self.labelOutputRB = QtGui.QLabel(self.crossOutputTab)
        self.labelOutputRB.setGeometry(QtCore.QRect(450, 430, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputRB.setFont(font)
        self.labelOutputRB.setObjectName(_fromUtf8("labelOutputRB"))
        self.imageCrossRG = QtGui.QGraphicsView(self.crossOutputTab)
        self.imageCrossRG.setGeometry(QtCore.QRect(10, 130, 311, 301))
        self.imageCrossRG.setObjectName(_fromUtf8("imageCrossRG"))
        self.labelOutputRG = QtGui.QLabel(self.crossOutputTab)
        self.labelOutputRG.setGeometry(QtCore.QRect(120, 430, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputRG.setFont(font)
        self.labelOutputRG.setObjectName(_fromUtf8("labelOutputRG"))
        self.imageCrossRB = QtGui.QGraphicsView(self.crossOutputTab)
        self.imageCrossRB.setGeometry(QtCore.QRect(330, 130, 311, 301))
        self.imageCrossRB.setObjectName(_fromUtf8("imageCrossRB"))
        self.labelOutputGB = QtGui.QLabel(self.crossOutputTab)
        self.labelOutputGB.setGeometry(QtCore.QRect(760, 430, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputGB.setFont(font)
        self.labelOutputGB.setObjectName(_fromUtf8("labelOutputGB"))
        self.imageCrossGB = QtGui.QGraphicsView(self.crossOutputTab)
        self.imageCrossGB.setGeometry(QtCore.QRect(650, 130, 311, 301))
        self.imageCrossGB.setObjectName(_fromUtf8("imageCrossGB"))
        self.labelCrossResNorm = QtGui.QLabel(self.crossOutputTab)
        self.labelCrossResNorm.setGeometry(QtCore.QRect(380, 500, 91, 31))
        self.labelCrossResNorm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCrossResNorm.setObjectName(_fromUtf8("labelCrossResNorm"))
        self.crossResNormValue = QtGui.QLabel(self.crossOutputTab)
        self.crossResNormValue.setGeometry(QtCore.QRect(480, 500, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.crossResNormValue.setFont(font)
        self.crossResNormValue.setFrameShape(QtGui.QFrame.Box)
        self.crossResNormValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.crossResNormValue.setText(_fromUtf8(""))
        self.crossResNormValue.setAlignment(QtCore.Qt.AlignCenter)
        self.crossResNormValue.setObjectName(_fromUtf8("crossResNormValue"))
        self.outputCorrelationTabWidget.addTab(self.crossOutputTab, _fromUtf8(""))
        self.tripleOutputTab = QtGui.QWidget()
        self.tripleOutputTab.setObjectName(_fromUtf8("tripleOutputTab"))
        self.labelOutputTripleFourier = QtGui.QLabel(self.tripleOutputTab)
        self.labelOutputTripleFourier.setGeometry(QtCore.QRect(70, 410, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputTripleFourier.setFont(font)
        self.labelOutputTripleFourier.setObjectName(_fromUtf8("labelOutputTripleFourier"))
        self.line_2 = QtGui.QFrame(self.tripleOutputTab)
        self.line_2.setGeometry(QtCore.QRect(300, 10, 20, 591))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.tripleOutputStartingPoint = QtGui.QLabel(self.tripleOutputTab)
        self.tripleOutputStartingPoint.setGeometry(QtCore.QRect(360, 11, 111, 20))
        self.tripleOutputStartingPoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tripleOutputStartingPoint.setObjectName(_fromUtf8("tripleOutputStartingPoint"))
        self.labelOutputBispectrum = QtGui.QLabel(self.tripleOutputTab)
        self.labelOutputBispectrum.setGeometry(QtCore.QRect(440, 300, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputBispectrum.setFont(font)
        self.labelOutputBispectrum.setObjectName(_fromUtf8("labelOutputBispectrum"))
        self.labelOutputTripleCorrelation3D = QtGui.QLabel(self.tripleOutputTab)
        self.labelOutputTripleCorrelation3D.setGeometry(QtCore.QRect(410, 590, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputTripleCorrelation3D.setFont(font)
        self.labelOutputTripleCorrelation3D.setObjectName(_fromUtf8("labelOutputTripleCorrelation3D"))
        self.line_3 = QtGui.QFrame(self.tripleOutputTab)
        self.line_3.setGeometry(QtCore.QRect(640, 10, 20, 591))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.tripleOutputRange = QtGui.QLabel(self.tripleOutputTab)
        self.tripleOutputRange.setGeometry(QtCore.QRect(710, 100, 61, 31))
        self.tripleOutputRange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tripleOutputRange.setObjectName(_fromUtf8("tripleOutputRange"))
        self.labelOutputTripleCorrelation = QtGui.QLabel(self.tripleOutputTab)
        self.labelOutputTripleCorrelation.setGeometry(QtCore.QRect(750, 410, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputTripleCorrelation.setFont(font)
        self.labelOutputTripleCorrelation.setObjectName(_fromUtf8("labelOutputTripleCorrelation"))
        self.imageTripleFourier = QtGui.QGraphicsView(self.tripleOutputTab)
        self.imageTripleFourier.setGeometry(QtCore.QRect(10, 140, 281, 271))
        self.imageTripleFourier.setObjectName(_fromUtf8("imageTripleFourier"))
        self.imageTripleBispectrum = QtGui.QGraphicsView(self.tripleOutputTab)
        self.imageTripleBispectrum.setGeometry(QtCore.QRect(350, 40, 271, 261))
        self.imageTripleBispectrum.setObjectName(_fromUtf8("imageTripleBispectrum"))
        self.imageTripleCorrelation3D = QtGui.QGraphicsView(self.tripleOutputTab)
        self.imageTripleCorrelation3D.setGeometry(QtCore.QRect(350, 330, 271, 261))
        self.imageTripleCorrelation3D.setObjectName(_fromUtf8("imageTripleCorrelation3D"))
        self.imageTripleCorrelation = QtGui.QGraphicsView(self.tripleOutputTab)
        self.imageTripleCorrelation.setGeometry(QtCore.QRect(670, 140, 281, 271))
        self.imageTripleCorrelation.setObjectName(_fromUtf8("imageTripleCorrelation"))
        self.labelTripleResNorm = QtGui.QLabel(self.tripleOutputTab)
        self.labelTripleResNorm.setGeometry(QtCore.QRect(30, 510, 91, 31))
        self.labelTripleResNorm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTripleResNorm.setObjectName(_fromUtf8("labelTripleResNorm"))
        self.tripleResNormValue = QtGui.QLabel(self.tripleOutputTab)
        self.tripleResNormValue.setGeometry(QtCore.QRect(130, 510, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tripleResNormValue.setFont(font)
        self.tripleResNormValue.setFrameShape(QtGui.QFrame.Box)
        self.tripleResNormValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.tripleResNormValue.setText(_fromUtf8(""))
        self.tripleResNormValue.setAlignment(QtCore.Qt.AlignCenter)
        self.tripleResNormValue.setObjectName(_fromUtf8("tripleResNormValue"))
        self.startingPointValue = QtGui.QLabel(self.tripleOutputTab)
        self.startingPointValue.setGeometry(QtCore.QRect(480, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.startingPointValue.setFont(font)
        self.startingPointValue.setFrameShape(QtGui.QFrame.Box)
        self.startingPointValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.startingPointValue.setText(_fromUtf8(""))
        self.startingPointValue.setAlignment(QtCore.Qt.AlignCenter)
        self.startingPointValue.setObjectName(_fromUtf8("startingPointValue"))
        self.rangeValue = QtGui.QLabel(self.tripleOutputTab)
        self.rangeValue.setGeometry(QtCore.QRect(790, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rangeValue.setFont(font)
        self.rangeValue.setFrameShape(QtGui.QFrame.Box)
        self.rangeValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.rangeValue.setText(_fromUtf8(""))
        self.rangeValue.setAlignment(QtCore.Qt.AlignCenter)
        self.rangeValue.setObjectName(_fromUtf8("rangeValue"))
        self.outputCorrelationTabWidget.addTab(self.tripleOutputTab, _fromUtf8(""))
        self.mainTabWidget.addTab(self.outputTab, _fromUtf8(""))
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(300, 720, 461, 23))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))

        self.retranslateUi(Dialog)
        self.mainTabWidget.setCurrentIndex(0)
        self.imageSettingsTabWidget.setCurrentIndex(0)
        self.correlationTabWidget.setCurrentIndex(0)
        self.outputCorrelationTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Image Correlation Spectroscopy", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("Dialog", "START", None, QtGui.QApplication.UnicodeUTF8))
        self.restartButton.setText(QtGui.QApplication.translate("Dialog", "RESTART", None, QtGui.QApplication.UnicodeUTF8))
        self.batchModeButton.setText(QtGui.QApplication.translate("Dialog", "SWITCH TO BATCH MODE", None, QtGui.QApplication.UnicodeUTF8))
        self.imageGroup.setTitle(QtGui.QApplication.translate("Dialog", "Images", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRGB.setText(QtGui.QApplication.translate("Dialog", "All Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRed.setText(QtGui.QApplication.translate("Dialog", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGreen.setText(QtGui.QApplication.translate("Dialog", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBlue.setText(QtGui.QApplication.translate("Dialog", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSettingsGroup.setTitle(QtGui.QApplication.translate("Dialog", "Image Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.loadImageRed.setText(QtGui.QApplication.translate("Dialog", "Load Red Channel Image", None, QtGui.QApplication.UnicodeUTF8))
        self.loadImageGreen.setText(QtGui.QApplication.translate("Dialog", "Load Green Channel Image", None, QtGui.QApplication.UnicodeUTF8))
        self.loadImageBlue.setText(QtGui.QApplication.translate("Dialog", "Load Blue Channel Image", None, QtGui.QApplication.UnicodeUTF8))
        self.redChannelFile.setText(QtGui.QApplication.translate("Dialog", "<no file>", None, QtGui.QApplication.UnicodeUTF8))
        self.greenChannelFile.setText(QtGui.QApplication.translate("Dialog", "<no file>", None, QtGui.QApplication.UnicodeUTF8))
        self.blueChannelFile.setText(QtGui.QApplication.translate("Dialog", "<no file>", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSettingsTabWidget.setTabText(self.imageSettingsTabWidget.indexOf(self.loadThreeTab), QtGui.QApplication.translate("Dialog", "Three Channel Images", None, QtGui.QApplication.UnicodeUTF8))
        self.loadImageRGB.setText(QtGui.QApplication.translate("Dialog", "Load RGB Image", None, QtGui.QApplication.UnicodeUTF8))
        self.rgbFile.setText(QtGui.QApplication.translate("Dialog", "<no file>", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSettingsTabWidget.setTabText(self.imageSettingsTabWidget.indexOf(self.loadSingleTab), QtGui.QApplication.translate("Dialog", "Single RGB Image", None, QtGui.QApplication.UnicodeUTF8))
        self.attributesGroup.setTitle(QtGui.QApplication.translate("Dialog", "Image Attributes", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSizeLabel.setText(QtGui.QApplication.translate("Dialog", "Image Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.avgIntensityLabel.setText(QtGui.QApplication.translate("Dialog", "Average Intensity per Pixel:", None, QtGui.QApplication.UnicodeUTF8))
        self.redIntensityLabel.setText(QtGui.QApplication.translate("Dialog", "Red - ", None, QtGui.QApplication.UnicodeUTF8))
        self.redIntensityLabel_2.setText(QtGui.QApplication.translate("Dialog", "Green - ", None, QtGui.QApplication.UnicodeUTF8))
        self.redIntensityLabel_3.setText(QtGui.QApplication.translate("Dialog", "Blue -", None, QtGui.QApplication.UnicodeUTF8))
        self.correlationSettingsGroup.setTitle(QtGui.QApplication.translate("Dialog", "Correlation Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.autoChannelsGroup.setTitle(QtGui.QApplication.translate("Dialog", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.redCheckbox.setText(QtGui.QApplication.translate("Dialog", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.greenCheckbox.setText(QtGui.QApplication.translate("Dialog", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.blueCheckbox.setText(QtGui.QApplication.translate("Dialog", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.autoGroup.setTitle(QtGui.QApplication.translate("Dialog", "Auto-Correlation Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.autoRange.setText(QtGui.QApplication.translate("Dialog", "Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.autoG0.setText(QtGui.QApplication.translate("Dialog", "g(0):", None, QtGui.QApplication.UnicodeUTF8))
        self.autoW.setText(QtGui.QApplication.translate("Dialog", "w:", None, QtGui.QApplication.UnicodeUTF8))
        self.autoGinf.setText(QtGui.QApplication.translate("Dialog", "ginf:", None, QtGui.QApplication.UnicodeUTF8))
        self.correlationTabWidget.setTabText(self.correlationTabWidget.indexOf(self.autoCorrelationTab), QtGui.QApplication.translate("Dialog", "Auto-Correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.crossGroup.setTitle(QtGui.QApplication.translate("Dialog", "Cross-Correlation Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.crossRange.setText(QtGui.QApplication.translate("Dialog", "Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.crossG0.setText(QtGui.QApplication.translate("Dialog", "g(0):", None, QtGui.QApplication.UnicodeUTF8))
        self.crossW.setText(QtGui.QApplication.translate("Dialog", "w:", None, QtGui.QApplication.UnicodeUTF8))
        self.crossGinf.setText(QtGui.QApplication.translate("Dialog", "ginf:", None, QtGui.QApplication.UnicodeUTF8))
        self.crossChannelsGroup.setTitle(QtGui.QApplication.translate("Dialog", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.redGreenCheckbox.setText(QtGui.QApplication.translate("Dialog", "Red-Green", None, QtGui.QApplication.UnicodeUTF8))
        self.redBlueCheckbox.setText(QtGui.QApplication.translate("Dialog", "Red-Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.greenBlueCheckbox.setText(QtGui.QApplication.translate("Dialog", "Green-Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.correlationTabWidget.setTabText(self.correlationTabWidget.indexOf(self.crossCorrelationTab), QtGui.QApplication.translate("Dialog", "Cross-Correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.tripleGroup.setTitle(QtGui.QApplication.translate("Dialog", "Triple-Correlation Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.tripleRange.setText(QtGui.QApplication.translate("Dialog", "Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.tripleG0.setText(QtGui.QApplication.translate("Dialog", "g(0):", None, QtGui.QApplication.UnicodeUTF8))
        self.tripleW.setText(QtGui.QApplication.translate("Dialog", "w:", None, QtGui.QApplication.UnicodeUTF8))
        self.tripleGinf.setText(QtGui.QApplication.translate("Dialog", "ginf:", None, QtGui.QApplication.UnicodeUTF8))
        self.correlationTabWidget.setTabText(self.correlationTabWidget.indexOf(self.tripleCorrelationTab), QtGui.QApplication.translate("Dialog", "Triple-Correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.allTripleGroup.setTitle(QtGui.QApplication.translate("Dialog", "Triple-Correlation Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.allTripleRange.setText(QtGui.QApplication.translate("Dialog", "Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.allTripleG0.setText(QtGui.QApplication.translate("Dialog", "g(0):", None, QtGui.QApplication.UnicodeUTF8))
        self.allTripleW.setText(QtGui.QApplication.translate("Dialog", "w:", None, QtGui.QApplication.UnicodeUTF8))
        self.allTripleGinf.setText(QtGui.QApplication.translate("Dialog", "ginf:", None, QtGui.QApplication.UnicodeUTF8))
        self.allAutoCrossGroup.setTitle(QtGui.QApplication.translate("Dialog", "Auto/Cross Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.allAutoCrossRange.setText(QtGui.QApplication.translate("Dialog", "Range:", None, QtGui.QApplication.UnicodeUTF8))
        self.allAutoCrossG0.setText(QtGui.QApplication.translate("Dialog", "g(0):", None, QtGui.QApplication.UnicodeUTF8))
        self.allAutoCrossW.setText(QtGui.QApplication.translate("Dialog", "w:", None, QtGui.QApplication.UnicodeUTF8))
        self.allAutoCrossGinf.setText(QtGui.QApplication.translate("Dialog", "ginf:", None, QtGui.QApplication.UnicodeUTF8))
        self.correlationTabWidget.setTabText(self.correlationTabWidget.indexOf(self.allCorrelationsTab), QtGui.QApplication.translate("Dialog", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleResolutionLabel.setText(QtGui.QApplication.translate("Dialog", "Sample Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution32.setText(QtGui.QApplication.translate("Dialog", "32 x 32", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution48.setText(QtGui.QApplication.translate("Dialog", "48 x 48", None, QtGui.QApplication.UnicodeUTF8))
        self.resolution64.setText(QtGui.QApplication.translate("Dialog", "64 x 64", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Ready.", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.inputTab), QtGui.QApplication.translate("Dialog", "Input Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOutputRed.setText(QtGui.QApplication.translate("Dialog", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOutputGreen.setText(QtGui.QApplication.translate("Dialog", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOutputBlue.setText(QtGui.QApplication.translate("Dialog", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAutoResNorm.setText(QtGui.QApplication.translate("Dialog", "Res. Norm.", None, QtGui.QApplication.UnicodeUTF8))
        self.outputCorrelationTabWidget.setTabText(self.outputCorrelationTabWidget.indexOf(self.autoOutputTab), QtGui.QApplication.translate("Dialog", "Auto-Correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOutputRB.setText(QtGui.QApplication.translate("Dialog", "Red-Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOutputRG.setText(QtGui.QApplication.translate("Dialog", "Red-Green", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOutputGB.setText(QtGui.QApplication.translate("Dialog", "Green-Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCrossResNorm.setText(QtGui.QApplication.translate("Dialog", "Res. Norm.", None, QtGui.QApplication.UnicodeUTF8))
        self.outputCorrelationTabWidget.setTabText(self.outputCorrelationTabWidget.indexOf(self.crossOutputTab), QtGui.QApplication.translate("Dialog", "Cross-Correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOutputTripleFourier.setText(QtGui.QApplication.translate("Dialog", "Fourier Transform (Red)", None, QtGui.QApplication.UnicodeUTF8))
        self.tripleOutputStartingPoint.setText(QtGui.QApplication.translate("Dialog", "Starting Point", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOutputBispectrum.setText(QtGui.QApplication.translate("Dialog", "Bispectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOutputTripleCorrelation3D.setText(QtGui.QApplication.translate("Dialog", "Triple-Correlation (3D)", None, QtGui.QApplication.UnicodeUTF8))
        self.tripleOutputRange.setText(QtGui.QApplication.translate("Dialog", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOutputTripleCorrelation.setText(QtGui.QApplication.translate("Dialog", "Triple-Correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTripleResNorm.setText(QtGui.QApplication.translate("Dialog", "Res. Norm.", None, QtGui.QApplication.UnicodeUTF8))
        self.outputCorrelationTabWidget.setTabText(self.outputCorrelationTabWidget.indexOf(self.tripleOutputTab), QtGui.QApplication.translate("Dialog", "Triple-Correlation", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.outputTab), QtGui.QApplication.translate("Dialog", "Output", None, QtGui.QApplication.UnicodeUTF8))

