# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainv6.ui'
#
# Created: Thu Mar 14 12:22:34 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1024, 670)
        Dialog.setAutoFillBackground(False)
        self.startButton = QtGui.QPushButton(Dialog)
        self.startButton.setEnabled(True)
        self.startButton.setGeometry(QtCore.QRect(10, 620, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.startButton.setFont(font)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.stopButton = QtGui.QPushButton(Dialog)
        self.stopButton.setEnabled(False)
        self.stopButton.setGeometry(QtCore.QRect(160, 620, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.batchModeButton = QtGui.QPushButton(Dialog)
        self.batchModeButton.setGeometry(QtCore.QRect(780, 620, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.batchModeButton.setFont(font)
        self.batchModeButton.setObjectName(_fromUtf8("batchModeButton"))
        self.mainTabWidget = QtGui.QTabWidget(Dialog)
        self.mainTabWidget.setGeometry(QtCore.QRect(0, 10, 1021, 601))
        self.mainTabWidget.setObjectName(_fromUtf8("mainTabWidget"))
        self.inputTab = QtGui.QWidget()
        self.inputTab.setObjectName(_fromUtf8("inputTab"))
        self.imageGroup = QtGui.QGroupBox(self.inputTab)
        self.imageGroup.setGeometry(QtCore.QRect(10, 0, 981, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imageGroup.setFont(font)
        self.imageGroup.setFlat(False)
        self.imageGroup.setCheckable(False)
        self.imageGroup.setObjectName(_fromUtf8("imageGroup"))
        self.labelRGB = QtGui.QLabel(self.imageGroup)
        self.labelRGB.setGeometry(QtCore.QRect(80, 220, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelRGB.setFont(font)
        self.labelRGB.setObjectName(_fromUtf8("labelRGB"))
        self.labelRed = QtGui.QLabel(self.imageGroup)
        self.labelRed.setGeometry(QtCore.QRect(350, 220, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelRed.setFont(font)
        self.labelRed.setObjectName(_fromUtf8("labelRed"))
        self.labelGreen = QtGui.QLabel(self.imageGroup)
        self.labelGreen.setGeometry(QtCore.QRect(580, 220, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelGreen.setFont(font)
        self.labelGreen.setObjectName(_fromUtf8("labelGreen"))
        self.labelBlue = QtGui.QLabel(self.imageGroup)
        self.labelBlue.setGeometry(QtCore.QRect(830, 220, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelBlue.setFont(font)
        self.labelBlue.setObjectName(_fromUtf8("labelBlue"))
        self.imageRgb = QtGui.QLabel(self.imageGroup)
        self.imageRgb.setGeometry(QtCore.QRect(40, 30, 192, 192))
        self.imageRgb.setFrameShape(QtGui.QFrame.Panel)
        self.imageRgb.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageRgb.setLineWidth(1)
        self.imageRgb.setText(_fromUtf8(""))
        self.imageRgb.setPixmap(QtGui.QPixmap(_fromUtf8("images/rgb.png")))
        self.imageRgb.setScaledContents(True)
        self.imageRgb.setObjectName(_fromUtf8("imageRgb"))
        self.imageRed = QtGui.QLabel(self.imageGroup)
        self.imageRed.setGeometry(QtCore.QRect(280, 30, 192, 192))
        self.imageRed.setFrameShape(QtGui.QFrame.Panel)
        self.imageRed.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageRed.setLineWidth(1)
        self.imageRed.setText(_fromUtf8(""))
        self.imageRed.setPixmap(QtGui.QPixmap(_fromUtf8("images/r.png")))
        self.imageRed.setScaledContents(True)
        self.imageRed.setObjectName(_fromUtf8("imageRed"))
        self.imageGreen = QtGui.QLabel(self.imageGroup)
        self.imageGreen.setGeometry(QtCore.QRect(520, 30, 192, 192))
        self.imageGreen.setFrameShape(QtGui.QFrame.Panel)
        self.imageGreen.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageGreen.setLineWidth(1)
        self.imageGreen.setText(_fromUtf8(""))
        self.imageGreen.setPixmap(QtGui.QPixmap(_fromUtf8("images/g.png")))
        self.imageGreen.setScaledContents(True)
        self.imageGreen.setObjectName(_fromUtf8("imageGreen"))
        self.imageBlue = QtGui.QLabel(self.imageGroup)
        self.imageBlue.setGeometry(QtCore.QRect(760, 30, 192, 192))
        self.imageBlue.setFrameShape(QtGui.QFrame.Panel)
        self.imageBlue.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageBlue.setLineWidth(1)
        self.imageBlue.setText(_fromUtf8(""))
        self.imageBlue.setPixmap(QtGui.QPixmap(_fromUtf8("images/b.png")))
        self.imageBlue.setScaledContents(True)
        self.imageBlue.setObjectName(_fromUtf8("imageBlue"))
        self.imageSettingsGroup = QtGui.QGroupBox(self.inputTab)
        self.imageSettingsGroup.setGeometry(QtCore.QRect(10, 250, 361, 191))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imageSettingsGroup.setFont(font)
        self.imageSettingsGroup.setObjectName(_fromUtf8("imageSettingsGroup"))
        self.imageSettingsTabWidget = QtGui.QTabWidget(self.imageSettingsGroup)
        self.imageSettingsTabWidget.setGeometry(QtCore.QRect(10, 20, 341, 161))
        self.imageSettingsTabWidget.setObjectName(_fromUtf8("imageSettingsTabWidget"))
        self.loadThreeTab = QtGui.QWidget()
        self.loadThreeTab.setObjectName(_fromUtf8("loadThreeTab"))
        self.loadImageRed = QtGui.QPushButton(self.loadThreeTab)
        self.loadImageRed.setGeometry(QtCore.QRect(10, 10, 211, 31))
        self.loadImageRed.setObjectName(_fromUtf8("loadImageRed"))
        self.loadImageGreen = QtGui.QPushButton(self.loadThreeTab)
        self.loadImageGreen.setGeometry(QtCore.QRect(10, 50, 211, 31))
        self.loadImageGreen.setObjectName(_fromUtf8("loadImageGreen"))
        self.loadImageBlue = QtGui.QPushButton(self.loadThreeTab)
        self.loadImageBlue.setGeometry(QtCore.QRect(10, 90, 211, 31))
        self.loadImageBlue.setObjectName(_fromUtf8("loadImageBlue"))
        self.redChannelFile = QtGui.QLabel(self.loadThreeTab)
        self.redChannelFile.setGeometry(QtCore.QRect(230, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.redChannelFile.setFont(font)
        self.redChannelFile.setFrameShape(QtGui.QFrame.Box)
        self.redChannelFile.setFrameShadow(QtGui.QFrame.Sunken)
        self.redChannelFile.setAlignment(QtCore.Qt.AlignCenter)
        self.redChannelFile.setObjectName(_fromUtf8("redChannelFile"))
        self.greenChannelFile = QtGui.QLabel(self.loadThreeTab)
        self.greenChannelFile.setGeometry(QtCore.QRect(230, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.greenChannelFile.setFont(font)
        self.greenChannelFile.setFrameShape(QtGui.QFrame.Box)
        self.greenChannelFile.setFrameShadow(QtGui.QFrame.Sunken)
        self.greenChannelFile.setAlignment(QtCore.Qt.AlignCenter)
        self.greenChannelFile.setObjectName(_fromUtf8("greenChannelFile"))
        self.blueChannelFile = QtGui.QLabel(self.loadThreeTab)
        self.blueChannelFile.setGeometry(QtCore.QRect(230, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.blueChannelFile.setFont(font)
        self.blueChannelFile.setFrameShape(QtGui.QFrame.Box)
        self.blueChannelFile.setFrameShadow(QtGui.QFrame.Sunken)
        self.blueChannelFile.setAlignment(QtCore.Qt.AlignCenter)
        self.blueChannelFile.setObjectName(_fromUtf8("blueChannelFile"))
        self.imageSettingsTabWidget.addTab(self.loadThreeTab, _fromUtf8(""))
        self.loadSingleTab = QtGui.QWidget()
        self.loadSingleTab.setObjectName(_fromUtf8("loadSingleTab"))
        self.loadImageRGB = QtGui.QPushButton(self.loadSingleTab)
        self.loadImageRGB.setGeometry(QtCore.QRect(50, 10, 221, 31))
        self.loadImageRGB.setObjectName(_fromUtf8("loadImageRGB"))
        self.rgbFile = QtGui.QLabel(self.loadSingleTab)
        self.rgbFile.setGeometry(QtCore.QRect(50, 70, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rgbFile.setFont(font)
        self.rgbFile.setFrameShape(QtGui.QFrame.Box)
        self.rgbFile.setFrameShadow(QtGui.QFrame.Sunken)
        self.rgbFile.setAlignment(QtCore.Qt.AlignCenter)
        self.rgbFile.setObjectName(_fromUtf8("rgbFile"))
        self.imageSettingsTabWidget.addTab(self.loadSingleTab, _fromUtf8(""))
        self.attributesGroup = QtGui.QGroupBox(self.inputTab)
        self.attributesGroup.setGeometry(QtCore.QRect(10, 440, 361, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.attributesGroup.setFont(font)
        self.attributesGroup.setObjectName(_fromUtf8("attributesGroup"))
        self.imageSizeLabel = QtGui.QLabel(self.attributesGroup)
        self.imageSizeLabel.setGeometry(QtCore.QRect(10, 40, 101, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.imageSizeLabel.setFont(font)
        self.imageSizeLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.imageSizeLabel.setObjectName(_fromUtf8("imageSizeLabel"))
        self.imageSizeText = QtGui.QLabel(self.attributesGroup)
        self.imageSizeText.setGeometry(QtCore.QRect(10, 70, 91, 21))
        self.imageSizeText.setFrameShape(QtGui.QFrame.Box)
        self.imageSizeText.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageSizeText.setText(_fromUtf8(""))
        self.imageSizeText.setObjectName(_fromUtf8("imageSizeText"))
        self.avgIntensityLabel = QtGui.QLabel(self.attributesGroup)
        self.avgIntensityLabel.setGeometry(QtCore.QRect(180, 5, 131, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.avgIntensityLabel.setFont(font)
        self.avgIntensityLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.avgIntensityLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.avgIntensityLabel.setWordWrap(True)
        self.avgIntensityLabel.setObjectName(_fromUtf8("avgIntensityLabel"))
        self.redIntensityLabel = QtGui.QLabel(self.attributesGroup)
        self.redIntensityLabel.setGeometry(QtCore.QRect(170, 50, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.redIntensityLabel.setFont(font)
        self.redIntensityLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.redIntensityLabel.setObjectName(_fromUtf8("redIntensityLabel"))
        self.greenIntensityLabel = QtGui.QLabel(self.attributesGroup)
        self.greenIntensityLabel.setGeometry(QtCore.QRect(160, 70, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.greenIntensityLabel.setFont(font)
        self.greenIntensityLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.greenIntensityLabel.setObjectName(_fromUtf8("greenIntensityLabel"))
        self.blueIntensityLabel = QtGui.QLabel(self.attributesGroup)
        self.blueIntensityLabel.setGeometry(QtCore.QRect(170, 90, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.blueIntensityLabel.setFont(font)
        self.blueIntensityLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.blueIntensityLabel.setObjectName(_fromUtf8("blueIntensityLabel"))
        self.redIntensityText = QtGui.QLabel(self.attributesGroup)
        self.redIntensityText.setGeometry(QtCore.QRect(220, 50, 91, 21))
        self.redIntensityText.setFrameShape(QtGui.QFrame.Box)
        self.redIntensityText.setFrameShadow(QtGui.QFrame.Sunken)
        self.redIntensityText.setText(_fromUtf8(""))
        self.redIntensityText.setObjectName(_fromUtf8("redIntensityText"))
        self.greenIntensityText = QtGui.QLabel(self.attributesGroup)
        self.greenIntensityText.setGeometry(QtCore.QRect(220, 70, 91, 21))
        self.greenIntensityText.setFrameShape(QtGui.QFrame.Box)
        self.greenIntensityText.setFrameShadow(QtGui.QFrame.Sunken)
        self.greenIntensityText.setText(_fromUtf8(""))
        self.greenIntensityText.setObjectName(_fromUtf8("greenIntensityText"))
        self.blueIntensityText = QtGui.QLabel(self.attributesGroup)
        self.blueIntensityText.setGeometry(QtCore.QRect(220, 90, 91, 21))
        self.blueIntensityText.setFrameShape(QtGui.QFrame.Box)
        self.blueIntensityText.setFrameShadow(QtGui.QFrame.Sunken)
        self.blueIntensityText.setText(_fromUtf8(""))
        self.blueIntensityText.setObjectName(_fromUtf8("blueIntensityText"))
        self.attributesDivider = QtGui.QFrame(self.attributesGroup)
        self.attributesDivider.setGeometry(QtCore.QRect(110, 20, 20, 91))
        self.attributesDivider.setFrameShape(QtGui.QFrame.VLine)
        self.attributesDivider.setFrameShadow(QtGui.QFrame.Sunken)
        self.attributesDivider.setObjectName(_fromUtf8("attributesDivider"))
        self.correlationSettingsGroup = QtGui.QGroupBox(self.inputTab)
        self.correlationSettingsGroup.setGeometry(QtCore.QRect(380, 250, 631, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.correlationSettingsGroup.setFont(font)
        self.correlationSettingsGroup.setObjectName(_fromUtf8("correlationSettingsGroup"))
        self.correlationTabWidget = QtGui.QTabWidget(self.correlationSettingsGroup)
        self.correlationTabWidget.setGeometry(QtCore.QRect(10, 30, 611, 181))
        self.correlationTabWidget.setObjectName(_fromUtf8("correlationTabWidget"))
        self.autoCorrelationTab = QtGui.QWidget()
        self.autoCorrelationTab.setObjectName(_fromUtf8("autoCorrelationTab"))
        self.autoChannelsGroup = QtGui.QGroupBox(self.autoCorrelationTab)
        self.autoChannelsGroup.setGeometry(QtCore.QRect(10, 10, 121, 131))
        self.autoChannelsGroup.setObjectName(_fromUtf8("autoChannelsGroup"))
        self.redCheckbox = QtGui.QCheckBox(self.autoChannelsGroup)
        self.redCheckbox.setGeometry(QtCore.QRect(10, 30, 70, 17))
        self.redCheckbox.setChecked(True)
        self.redCheckbox.setObjectName(_fromUtf8("redCheckbox"))
        self.greenCheckbox = QtGui.QCheckBox(self.autoChannelsGroup)
        self.greenCheckbox.setGeometry(QtCore.QRect(10, 60, 70, 17))
        self.greenCheckbox.setChecked(True)
        self.greenCheckbox.setObjectName(_fromUtf8("greenCheckbox"))
        self.blueCheckbox = QtGui.QCheckBox(self.autoChannelsGroup)
        self.blueCheckbox.setGeometry(QtCore.QRect(10, 90, 70, 17))
        self.blueCheckbox.setChecked(True)
        self.blueCheckbox.setObjectName(_fromUtf8("blueCheckbox"))
        self.autoGroup = QtGui.QGroupBox(self.autoCorrelationTab)
        self.autoGroup.setGeometry(QtCore.QRect(140, 10, 341, 131))
        self.autoGroup.setFlat(False)
        self.autoGroup.setCheckable(False)
        self.autoGroup.setObjectName(_fromUtf8("autoGroup"))
        self.autoRangeLabel = QtGui.QLabel(self.autoGroup)
        self.autoRangeLabel.setGeometry(QtCore.QRect(10, 30, 61, 31))
        self.autoRangeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.autoRangeLabel.setObjectName(_fromUtf8("autoRangeLabel"))
        self.autoG0Label = QtGui.QLabel(self.autoGroup)
        self.autoG0Label.setGeometry(QtCore.QRect(10, 70, 61, 31))
        self.autoG0Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.autoG0Label.setObjectName(_fromUtf8("autoG0Label"))
        self.autoWLabel = QtGui.QLabel(self.autoGroup)
        self.autoWLabel.setGeometry(QtCore.QRect(200, 30, 21, 31))
        self.autoWLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.autoWLabel.setObjectName(_fromUtf8("autoWLabel"))
        self.autoGinfLabel = QtGui.QLabel(self.autoGroup)
        self.autoGinfLabel.setGeometry(QtCore.QRect(180, 70, 41, 31))
        self.autoGinfLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.autoGinfLabel.setObjectName(_fromUtf8("autoGinfLabel"))
        self.autoRangeTextbox = QtGui.QLineEdit(self.autoGroup)
        self.autoRangeTextbox.setGeometry(QtCore.QRect(80, 30, 91, 31))
        self.autoRangeTextbox.setObjectName(_fromUtf8("autoRangeTextbox"))
        self.autoG0Textbox = QtGui.QLineEdit(self.autoGroup)
        self.autoG0Textbox.setGeometry(QtCore.QRect(80, 70, 91, 31))
        self.autoG0Textbox.setObjectName(_fromUtf8("autoG0Textbox"))
        self.autoWTextbox = QtGui.QLineEdit(self.autoGroup)
        self.autoWTextbox.setGeometry(QtCore.QRect(230, 30, 91, 31))
        self.autoWTextbox.setObjectName(_fromUtf8("autoWTextbox"))
        self.autoGinfTextbox = QtGui.QLineEdit(self.autoGroup)
        self.autoGinfTextbox.setGeometry(QtCore.QRect(230, 70, 91, 31))
        self.autoGinfTextbox.setObjectName(_fromUtf8("autoGinfTextbox"))
        self.autoDeltasCheckbox = QtGui.QCheckBox(self.autoGroup)
        self.autoDeltasCheckbox.setGeometry(QtCore.QRect(150, 110, 171, 17))
        self.autoDeltasCheckbox.setObjectName(_fromUtf8("autoDeltasCheckbox"))
        self.correlationTabWidget.addTab(self.autoCorrelationTab, _fromUtf8(""))
        self.crossCorrelationTab = QtGui.QWidget()
        self.crossCorrelationTab.setObjectName(_fromUtf8("crossCorrelationTab"))
        self.crossGroup = QtGui.QGroupBox(self.crossCorrelationTab)
        self.crossGroup.setGeometry(QtCore.QRect(140, 10, 341, 131))
        self.crossGroup.setFlat(False)
        self.crossGroup.setCheckable(False)
        self.crossGroup.setObjectName(_fromUtf8("crossGroup"))
        self.crossRangeLabel = QtGui.QLabel(self.crossGroup)
        self.crossRangeLabel.setGeometry(QtCore.QRect(10, 30, 61, 31))
        self.crossRangeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.crossRangeLabel.setObjectName(_fromUtf8("crossRangeLabel"))
        self.crossG0Label = QtGui.QLabel(self.crossGroup)
        self.crossG0Label.setGeometry(QtCore.QRect(-20, 70, 91, 31))
        self.crossG0Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.crossG0Label.setObjectName(_fromUtf8("crossG0Label"))
        self.crossWLabel = QtGui.QLabel(self.crossGroup)
        self.crossWLabel.setGeometry(QtCore.QRect(190, 30, 31, 31))
        self.crossWLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.crossWLabel.setObjectName(_fromUtf8("crossWLabel"))
        self.crossGinfLabel = QtGui.QLabel(self.crossGroup)
        self.crossGinfLabel.setGeometry(QtCore.QRect(180, 70, 41, 31))
        self.crossGinfLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.crossGinfLabel.setObjectName(_fromUtf8("crossGinfLabel"))
        self.crossRangeTextbox = QtGui.QLineEdit(self.crossGroup)
        self.crossRangeTextbox.setGeometry(QtCore.QRect(80, 30, 91, 31))
        self.crossRangeTextbox.setObjectName(_fromUtf8("crossRangeTextbox"))
        self.crossG0Textbox = QtGui.QLineEdit(self.crossGroup)
        self.crossG0Textbox.setGeometry(QtCore.QRect(80, 70, 91, 31))
        self.crossG0Textbox.setObjectName(_fromUtf8("crossG0Textbox"))
        self.crossWTextbox = QtGui.QLineEdit(self.crossGroup)
        self.crossWTextbox.setGeometry(QtCore.QRect(230, 30, 91, 31))
        self.crossWTextbox.setObjectName(_fromUtf8("crossWTextbox"))
        self.crossGinfTextbox = QtGui.QLineEdit(self.crossGroup)
        self.crossGinfTextbox.setGeometry(QtCore.QRect(230, 70, 91, 31))
        self.crossGinfTextbox.setObjectName(_fromUtf8("crossGinfTextbox"))
        self.crossChannelsGroup = QtGui.QGroupBox(self.crossCorrelationTab)
        self.crossChannelsGroup.setGeometry(QtCore.QRect(10, 10, 121, 131))
        self.crossChannelsGroup.setObjectName(_fromUtf8("crossChannelsGroup"))
        self.redGreenCheckbox = QtGui.QCheckBox(self.crossChannelsGroup)
        self.redGreenCheckbox.setGeometry(QtCore.QRect(10, 30, 111, 17))
        self.redGreenCheckbox.setChecked(True)
        self.redGreenCheckbox.setObjectName(_fromUtf8("redGreenCheckbox"))
        self.redBlueCheckbox = QtGui.QCheckBox(self.crossChannelsGroup)
        self.redBlueCheckbox.setGeometry(QtCore.QRect(10, 60, 91, 17))
        self.redBlueCheckbox.setChecked(True)
        self.redBlueCheckbox.setObjectName(_fromUtf8("redBlueCheckbox"))
        self.greenBlueCheckbox = QtGui.QCheckBox(self.crossChannelsGroup)
        self.greenBlueCheckbox.setGeometry(QtCore.QRect(10, 90, 111, 17))
        self.greenBlueCheckbox.setChecked(True)
        self.greenBlueCheckbox.setObjectName(_fromUtf8("greenBlueCheckbox"))
        self.crossDeltasCheckbox = QtGui.QCheckBox(self.crossCorrelationTab)
        self.crossDeltasCheckbox.setGeometry(QtCore.QRect(290, 120, 171, 17))
        self.crossDeltasCheckbox.setObjectName(_fromUtf8("crossDeltasCheckbox"))
        self.correlationTabWidget.addTab(self.crossCorrelationTab, _fromUtf8(""))
        self.tripleCorrelationTab = QtGui.QWidget()
        self.tripleCorrelationTab.setObjectName(_fromUtf8("tripleCorrelationTab"))
        self.label = QtGui.QLabel(self.tripleCorrelationTab)
        self.label.setGeometry(QtCore.QRect(60, 30, 391, 71))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.correlationTabWidget.addTab(self.tripleCorrelationTab, _fromUtf8(""))
        self.allCorrelationsTab = QtGui.QWidget()
        self.allCorrelationsTab.setObjectName(_fromUtf8("allCorrelationsTab"))
        self.allAutoCrossGroup = QtGui.QGroupBox(self.allCorrelationsTab)
        self.allAutoCrossGroup.setGeometry(QtCore.QRect(140, 10, 341, 131))
        self.allAutoCrossGroup.setFlat(False)
        self.allAutoCrossGroup.setCheckable(False)
        self.allAutoCrossGroup.setObjectName(_fromUtf8("allAutoCrossGroup"))
        self.allAutoCrossRangeLabel = QtGui.QLabel(self.allAutoCrossGroup)
        self.allAutoCrossRangeLabel.setGeometry(QtCore.QRect(20, 30, 51, 31))
        self.allAutoCrossRangeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allAutoCrossRangeLabel.setObjectName(_fromUtf8("allAutoCrossRangeLabel"))
        self.allAutoCrossG0Label = QtGui.QLabel(self.allAutoCrossGroup)
        self.allAutoCrossG0Label.setGeometry(QtCore.QRect(20, 70, 51, 31))
        self.allAutoCrossG0Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allAutoCrossG0Label.setObjectName(_fromUtf8("allAutoCrossG0Label"))
        self.allAutoCrossWLabel = QtGui.QLabel(self.allAutoCrossGroup)
        self.allAutoCrossWLabel.setGeometry(QtCore.QRect(200, 30, 21, 31))
        self.allAutoCrossWLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allAutoCrossWLabel.setObjectName(_fromUtf8("allAutoCrossWLabel"))
        self.allAutoCrossGinfLabel = QtGui.QLabel(self.allAutoCrossGroup)
        self.allAutoCrossGinfLabel.setGeometry(QtCore.QRect(170, 70, 51, 31))
        self.allAutoCrossGinfLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.allAutoCrossGinfLabel.setObjectName(_fromUtf8("allAutoCrossGinfLabel"))
        self.allAutoCrossRangeTextbox = QtGui.QLineEdit(self.allAutoCrossGroup)
        self.allAutoCrossRangeTextbox.setGeometry(QtCore.QRect(80, 30, 91, 31))
        self.allAutoCrossRangeTextbox.setObjectName(_fromUtf8("allAutoCrossRangeTextbox"))
        self.allAutoCrossG0Textbox = QtGui.QLineEdit(self.allAutoCrossGroup)
        self.allAutoCrossG0Textbox.setGeometry(QtCore.QRect(80, 70, 91, 31))
        self.allAutoCrossG0Textbox.setObjectName(_fromUtf8("allAutoCrossG0Textbox"))
        self.allAutoCrossWTextbox = QtGui.QLineEdit(self.allAutoCrossGroup)
        self.allAutoCrossWTextbox.setGeometry(QtCore.QRect(230, 30, 91, 31))
        self.allAutoCrossWTextbox.setObjectName(_fromUtf8("allAutoCrossWTextbox"))
        self.allAutoCrossGinfTextbox = QtGui.QLineEdit(self.allAutoCrossGroup)
        self.allAutoCrossGinfTextbox.setGeometry(QtCore.QRect(230, 70, 91, 31))
        self.allAutoCrossGinfTextbox.setObjectName(_fromUtf8("allAutoCrossGinfTextbox"))
        self.allDeltasCheckbox = QtGui.QCheckBox(self.allAutoCrossGroup)
        self.allDeltasCheckbox.setGeometry(QtCore.QRect(150, 110, 171, 17))
        self.allDeltasCheckbox.setObjectName(_fromUtf8("allDeltasCheckbox"))
        self.correlationTabWidget.addTab(self.allCorrelationsTab, _fromUtf8(""))
        self.messageBox = QtGui.QLabel(self.inputTab)
        self.messageBox.setGeometry(QtCore.QRect(380, 480, 631, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(10)
        self.messageBox.setFont(font)
        self.messageBox.setFrameShape(QtGui.QFrame.WinPanel)
        self.messageBox.setFrameShadow(QtGui.QFrame.Sunken)
        self.messageBox.setLineWidth(1)
        self.messageBox.setAlignment(QtCore.Qt.AlignCenter)
        self.messageBox.setWordWrap(True)
        self.messageBox.setObjectName(_fromUtf8("messageBox"))
        self.mainTabWidget.addTab(self.inputTab, _fromUtf8(""))
        self.outputTab = QtGui.QWidget()
        self.outputTab.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.outputTab.setObjectName(_fromUtf8("outputTab"))
        self.outputCorrelationTabWidget = QtGui.QTabWidget(self.outputTab)
        self.outputCorrelationTabWidget.setGeometry(QtCore.QRect(10, 10, 1001, 551))
        self.outputCorrelationTabWidget.setObjectName(_fromUtf8("outputCorrelationTabWidget"))
        self.autoOutputTab = QtGui.QWidget()
        self.autoOutputTab.setObjectName(_fromUtf8("autoOutputTab"))
        self.labelOutputRed = QtGui.QLabel(self.autoOutputTab)
        self.labelOutputRed.setGeometry(QtCore.QRect(140, 310, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputRed.setFont(font)
        self.labelOutputRed.setObjectName(_fromUtf8("labelOutputRed"))
        self.labelOutputGreen = QtGui.QLabel(self.autoOutputTab)
        self.labelOutputGreen.setGeometry(QtCore.QRect(460, 310, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputGreen.setFont(font)
        self.labelOutputGreen.setObjectName(_fromUtf8("labelOutputGreen"))
        self.labelOutputBlue = QtGui.QLabel(self.autoOutputTab)
        self.labelOutputBlue.setGeometry(QtCore.QRect(780, 310, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputBlue.setFont(font)
        self.labelOutputBlue.setObjectName(_fromUtf8("labelOutputBlue"))
        self.labelAutoResNorm = QtGui.QLabel(self.autoOutputTab)
        self.labelAutoResNorm.setGeometry(QtCore.QRect(370, 340, 91, 31))
        self.labelAutoResNorm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAutoResNorm.setObjectName(_fromUtf8("labelAutoResNorm"))
        self.autoResNormValue = QtGui.QLabel(self.autoOutputTab)
        self.autoResNormValue.setGeometry(QtCore.QRect(480, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.autoResNormValue.setFont(font)
        self.autoResNormValue.setFrameShape(QtGui.QFrame.Box)
        self.autoResNormValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.autoResNormValue.setText(_fromUtf8(""))
        self.autoResNormValue.setAlignment(QtCore.Qt.AlignCenter)
        self.autoResNormValue.setObjectName(_fromUtf8("autoResNormValue"))
        self.autoG0Value = QtGui.QLabel(self.autoOutputTab)
        self.autoG0Value.setGeometry(QtCore.QRect(480, 380, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.autoG0Value.setFont(font)
        self.autoG0Value.setFrameShape(QtGui.QFrame.Box)
        self.autoG0Value.setFrameShadow(QtGui.QFrame.Sunken)
        self.autoG0Value.setText(_fromUtf8(""))
        self.autoG0Value.setAlignment(QtCore.Qt.AlignCenter)
        self.autoG0Value.setObjectName(_fromUtf8("autoG0Value"))
        self.labelAutoG0 = QtGui.QLabel(self.autoOutputTab)
        self.labelAutoG0.setGeometry(QtCore.QRect(370, 380, 91, 31))
        self.labelAutoG0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAutoG0.setObjectName(_fromUtf8("labelAutoG0"))
        self.autoWValue = QtGui.QLabel(self.autoOutputTab)
        self.autoWValue.setGeometry(QtCore.QRect(480, 420, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.autoWValue.setFont(font)
        self.autoWValue.setFrameShape(QtGui.QFrame.Box)
        self.autoWValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.autoWValue.setText(_fromUtf8(""))
        self.autoWValue.setAlignment(QtCore.Qt.AlignCenter)
        self.autoWValue.setObjectName(_fromUtf8("autoWValue"))
        self.labelAutoW = QtGui.QLabel(self.autoOutputTab)
        self.labelAutoW.setGeometry(QtCore.QRect(370, 420, 91, 31))
        self.labelAutoW.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAutoW.setObjectName(_fromUtf8("labelAutoW"))
        self.autoGinfValue = QtGui.QLabel(self.autoOutputTab)
        self.autoGinfValue.setGeometry(QtCore.QRect(480, 460, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.autoGinfValue.setFont(font)
        self.autoGinfValue.setFrameShape(QtGui.QFrame.Box)
        self.autoGinfValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.autoGinfValue.setText(_fromUtf8(""))
        self.autoGinfValue.setAlignment(QtCore.Qt.AlignCenter)
        self.autoGinfValue.setObjectName(_fromUtf8("autoGinfValue"))
        self.labelAutoGinf = QtGui.QLabel(self.autoOutputTab)
        self.labelAutoGinf.setGeometry(QtCore.QRect(370, 460, 91, 31))
        self.labelAutoGinf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAutoGinf.setObjectName(_fromUtf8("labelAutoGinf"))
        self.imageAutoRed = QtGui.QLabel(self.autoOutputTab)
        self.imageAutoRed.setGeometry(QtCore.QRect(10, 10, 311, 301))
        self.imageAutoRed.setFrameShape(QtGui.QFrame.Panel)
        self.imageAutoRed.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageAutoRed.setText(_fromUtf8(""))
        self.imageAutoRed.setScaledContents(True)
        self.imageAutoRed.setObjectName(_fromUtf8("imageAutoRed"))
        self.imageAutoGreen = QtGui.QLabel(self.autoOutputTab)
        self.imageAutoGreen.setGeometry(QtCore.QRect(330, 10, 311, 301))
        self.imageAutoGreen.setFrameShape(QtGui.QFrame.Panel)
        self.imageAutoGreen.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageAutoGreen.setText(_fromUtf8(""))
        self.imageAutoGreen.setScaledContents(True)
        self.imageAutoGreen.setObjectName(_fromUtf8("imageAutoGreen"))
        self.imageAutoBlue = QtGui.QLabel(self.autoOutputTab)
        self.imageAutoBlue.setGeometry(QtCore.QRect(650, 10, 311, 301))
        self.imageAutoBlue.setFrameShape(QtGui.QFrame.Panel)
        self.imageAutoBlue.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageAutoBlue.setText(_fromUtf8(""))
        self.imageAutoBlue.setScaledContents(True)
        self.imageAutoBlue.setObjectName(_fromUtf8("imageAutoBlue"))
        self.autoDeltasUsedCheckbox = QtGui.QCheckBox(self.autoOutputTab)
        self.autoDeltasUsedCheckbox.setEnabled(False)
        self.autoDeltasUsedCheckbox.setGeometry(QtCore.QRect(620, 340, 131, 22))
        self.autoDeltasUsedCheckbox.setChecked(False)
        self.autoDeltasUsedCheckbox.setObjectName(_fromUtf8("autoDeltasUsedCheckbox"))
        self.outputCorrelationTabWidget.addTab(self.autoOutputTab, _fromUtf8(""))
        self.crossOutputTab = QtGui.QWidget()
        self.crossOutputTab.setObjectName(_fromUtf8("crossOutputTab"))
        self.labelOutputRB = QtGui.QLabel(self.crossOutputTab)
        self.labelOutputRB.setGeometry(QtCore.QRect(450, 310, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputRB.setFont(font)
        self.labelOutputRB.setObjectName(_fromUtf8("labelOutputRB"))
        self.labelOutputRG = QtGui.QLabel(self.crossOutputTab)
        self.labelOutputRG.setGeometry(QtCore.QRect(120, 310, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputRG.setFont(font)
        self.labelOutputRG.setObjectName(_fromUtf8("labelOutputRG"))
        self.labelOutputGB = QtGui.QLabel(self.crossOutputTab)
        self.labelOutputGB.setGeometry(QtCore.QRect(760, 310, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputGB.setFont(font)
        self.labelOutputGB.setObjectName(_fromUtf8("labelOutputGB"))
        self.labelCrossResNorm = QtGui.QLabel(self.crossOutputTab)
        self.labelCrossResNorm.setGeometry(QtCore.QRect(370, 340, 91, 31))
        self.labelCrossResNorm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCrossResNorm.setObjectName(_fromUtf8("labelCrossResNorm"))
        self.crossResNormValue = QtGui.QLabel(self.crossOutputTab)
        self.crossResNormValue.setGeometry(QtCore.QRect(480, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.crossResNormValue.setFont(font)
        self.crossResNormValue.setFrameShape(QtGui.QFrame.Box)
        self.crossResNormValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.crossResNormValue.setText(_fromUtf8(""))
        self.crossResNormValue.setAlignment(QtCore.Qt.AlignCenter)
        self.crossResNormValue.setObjectName(_fromUtf8("crossResNormValue"))
        self.labelCrossG0 = QtGui.QLabel(self.crossOutputTab)
        self.labelCrossG0.setGeometry(QtCore.QRect(370, 380, 91, 31))
        self.labelCrossG0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCrossG0.setObjectName(_fromUtf8("labelCrossG0"))
        self.crossG0Value = QtGui.QLabel(self.crossOutputTab)
        self.crossG0Value.setGeometry(QtCore.QRect(480, 380, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.crossG0Value.setFont(font)
        self.crossG0Value.setFrameShape(QtGui.QFrame.Box)
        self.crossG0Value.setFrameShadow(QtGui.QFrame.Sunken)
        self.crossG0Value.setText(_fromUtf8(""))
        self.crossG0Value.setAlignment(QtCore.Qt.AlignCenter)
        self.crossG0Value.setObjectName(_fromUtf8("crossG0Value"))
        self.labelCrossW = QtGui.QLabel(self.crossOutputTab)
        self.labelCrossW.setGeometry(QtCore.QRect(370, 420, 91, 31))
        self.labelCrossW.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCrossW.setObjectName(_fromUtf8("labelCrossW"))
        self.crossWValue = QtGui.QLabel(self.crossOutputTab)
        self.crossWValue.setGeometry(QtCore.QRect(480, 420, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.crossWValue.setFont(font)
        self.crossWValue.setFrameShape(QtGui.QFrame.Box)
        self.crossWValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.crossWValue.setText(_fromUtf8(""))
        self.crossWValue.setAlignment(QtCore.Qt.AlignCenter)
        self.crossWValue.setObjectName(_fromUtf8("crossWValue"))
        self.labelCrossGinf = QtGui.QLabel(self.crossOutputTab)
        self.labelCrossGinf.setGeometry(QtCore.QRect(370, 460, 91, 31))
        self.labelCrossGinf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCrossGinf.setObjectName(_fromUtf8("labelCrossGinf"))
        self.crossGinfValue = QtGui.QLabel(self.crossOutputTab)
        self.crossGinfValue.setGeometry(QtCore.QRect(480, 460, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.crossGinfValue.setFont(font)
        self.crossGinfValue.setFrameShape(QtGui.QFrame.Box)
        self.crossGinfValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.crossGinfValue.setText(_fromUtf8(""))
        self.crossGinfValue.setAlignment(QtCore.Qt.AlignCenter)
        self.crossGinfValue.setObjectName(_fromUtf8("crossGinfValue"))
        self.imageCrossRG = QtGui.QLabel(self.crossOutputTab)
        self.imageCrossRG.setGeometry(QtCore.QRect(10, 10, 311, 301))
        self.imageCrossRG.setFrameShape(QtGui.QFrame.Panel)
        self.imageCrossRG.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageCrossRG.setText(_fromUtf8(""))
        self.imageCrossRG.setScaledContents(True)
        self.imageCrossRG.setObjectName(_fromUtf8("imageCrossRG"))
        self.imageCrossRB = QtGui.QLabel(self.crossOutputTab)
        self.imageCrossRB.setGeometry(QtCore.QRect(330, 10, 311, 301))
        self.imageCrossRB.setFrameShape(QtGui.QFrame.Panel)
        self.imageCrossRB.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageCrossRB.setText(_fromUtf8(""))
        self.imageCrossRB.setScaledContents(True)
        self.imageCrossRB.setObjectName(_fromUtf8("imageCrossRB"))
        self.imageCrossGB = QtGui.QLabel(self.crossOutputTab)
        self.imageCrossGB.setGeometry(QtCore.QRect(650, 10, 311, 301))
        self.imageCrossGB.setFrameShape(QtGui.QFrame.Panel)
        self.imageCrossGB.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageCrossGB.setText(_fromUtf8(""))
        self.imageCrossGB.setScaledContents(True)
        self.imageCrossGB.setObjectName(_fromUtf8("imageCrossGB"))
        self.crossDeltasUsedCheckbox = QtGui.QCheckBox(self.crossOutputTab)
        self.crossDeltasUsedCheckbox.setEnabled(False)
        self.crossDeltasUsedCheckbox.setGeometry(QtCore.QRect(620, 340, 131, 22))
        self.crossDeltasUsedCheckbox.setChecked(False)
        self.crossDeltasUsedCheckbox.setObjectName(_fromUtf8("crossDeltasUsedCheckbox"))
        self.outputCorrelationTabWidget.addTab(self.crossOutputTab, _fromUtf8(""))
        self.tripleOutputTab = QtGui.QWidget()
        self.tripleOutputTab.setObjectName(_fromUtf8("tripleOutputTab"))
        self.labelOutputTripleFourier = QtGui.QLabel(self.tripleOutputTab)
        self.labelOutputTripleFourier.setGeometry(QtCore.QRect(70, 380, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputTripleFourier.setFont(font)
        self.labelOutputTripleFourier.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelOutputTripleFourier.setWordWrap(True)
        self.labelOutputTripleFourier.setObjectName(_fromUtf8("labelOutputTripleFourier"))
        self.tripleLeftDivider = QtGui.QFrame(self.tripleOutputTab)
        self.tripleLeftDivider.setGeometry(QtCore.QRect(300, 10, 20, 501))
        self.tripleLeftDivider.setFrameShape(QtGui.QFrame.VLine)
        self.tripleLeftDivider.setFrameShadow(QtGui.QFrame.Sunken)
        self.tripleLeftDivider.setObjectName(_fromUtf8("tripleLeftDivider"))
        self.labelOutputTripleCorrelation3D = QtGui.QLabel(self.tripleOutputTab)
        self.labelOutputTripleCorrelation3D.setGeometry(QtCore.QRect(410, 380, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputTripleCorrelation3D.setFont(font)
        self.labelOutputTripleCorrelation3D.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelOutputTripleCorrelation3D.setWordWrap(True)
        self.labelOutputTripleCorrelation3D.setObjectName(_fromUtf8("labelOutputTripleCorrelation3D"))
        self.tripleRightDivider = QtGui.QFrame(self.tripleOutputTab)
        self.tripleRightDivider.setGeometry(QtCore.QRect(640, 10, 20, 501))
        self.tripleRightDivider.setFrameShape(QtGui.QFrame.VLine)
        self.tripleRightDivider.setFrameShadow(QtGui.QFrame.Sunken)
        self.tripleRightDivider.setObjectName(_fromUtf8("tripleRightDivider"))
        self.labelOutputTripleCorrelation = QtGui.QLabel(self.tripleOutputTab)
        self.labelOutputTripleCorrelation.setGeometry(QtCore.QRect(730, 380, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOutputTripleCorrelation.setFont(font)
        self.labelOutputTripleCorrelation.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOutputTripleCorrelation.setObjectName(_fromUtf8("labelOutputTripleCorrelation"))
        self.labelTripleResNorm = QtGui.QLabel(self.tripleOutputTab)
        self.labelTripleResNorm.setGeometry(QtCore.QRect(840, 410, 91, 31))
        self.labelTripleResNorm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTripleResNorm.setObjectName(_fromUtf8("labelTripleResNorm"))
        self.tripleResNormValue = QtGui.QLabel(self.tripleOutputTab)
        self.tripleResNormValue.setGeometry(QtCore.QRect(850, 440, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tripleResNormValue.setFont(font)
        self.tripleResNormValue.setFrameShape(QtGui.QFrame.Box)
        self.tripleResNormValue.setFrameShadow(QtGui.QFrame.Sunken)
        self.tripleResNormValue.setText(_fromUtf8(""))
        self.tripleResNormValue.setAlignment(QtCore.Qt.AlignCenter)
        self.tripleResNormValue.setObjectName(_fromUtf8("tripleResNormValue"))
        self.tripleG0 = QtGui.QLabel(self.tripleOutputTab)
        self.tripleG0.setGeometry(QtCore.QRect(800, 10, 61, 31))
        self.tripleG0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tripleG0.setObjectName(_fromUtf8("tripleG0"))
        self.tripleW = QtGui.QLabel(self.tripleOutputTab)
        self.tripleW.setGeometry(QtCore.QRect(620, 50, 91, 31))
        self.tripleW.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tripleW.setObjectName(_fromUtf8("tripleW"))
        self.tripleGinfTextbox = QtGui.QLineEdit(self.tripleOutputTab)
        self.tripleGinfTextbox.setGeometry(QtCore.QRect(870, 50, 81, 31))
        self.tripleGinfTextbox.setObjectName(_fromUtf8("tripleGinfTextbox"))
        self.tripleG0Textbox = QtGui.QLineEdit(self.tripleOutputTab)
        self.tripleG0Textbox.setGeometry(QtCore.QRect(870, 10, 81, 31))
        self.tripleG0Textbox.setObjectName(_fromUtf8("tripleG0Textbox"))
        self.tripleRangeTextbox = QtGui.QLineEdit(self.tripleOutputTab)
        self.tripleRangeTextbox.setGeometry(QtCore.QRect(720, 10, 81, 31))
        self.tripleRangeTextbox.setObjectName(_fromUtf8("tripleRangeTextbox"))
        self.tripleRange = QtGui.QLabel(self.tripleOutputTab)
        self.tripleRange.setGeometry(QtCore.QRect(620, 10, 91, 31))
        self.tripleRange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tripleRange.setObjectName(_fromUtf8("tripleRange"))
        self.tripleGinf = QtGui.QLabel(self.tripleOutputTab)
        self.tripleGinf.setGeometry(QtCore.QRect(770, 50, 91, 31))
        self.tripleGinf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tripleGinf.setObjectName(_fromUtf8("tripleGinf"))
        self.tripleWTextbox = QtGui.QLineEdit(self.tripleOutputTab)
        self.tripleWTextbox.setGeometry(QtCore.QRect(720, 50, 81, 31))
        self.tripleWTextbox.setObjectName(_fromUtf8("tripleWTextbox"))
        self.imageTripleFourier = QtGui.QLabel(self.tripleOutputTab)
        self.imageTripleFourier.setGeometry(QtCore.QRect(10, 99, 281, 271))
        self.imageTripleFourier.setFrameShape(QtGui.QFrame.Panel)
        self.imageTripleFourier.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageTripleFourier.setText(_fromUtf8(""))
        self.imageTripleFourier.setScaledContents(True)
        self.imageTripleFourier.setObjectName(_fromUtf8("imageTripleFourier"))
        self.imageTripleCorrelation = QtGui.QLabel(self.tripleOutputTab)
        self.imageTripleCorrelation.setGeometry(QtCore.QRect(340, 99, 281, 271))
        self.imageTripleCorrelation.setFrameShape(QtGui.QFrame.Panel)
        self.imageTripleCorrelation.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageTripleCorrelation.setText(_fromUtf8(""))
        self.imageTripleCorrelation.setScaledContents(True)
        self.imageTripleCorrelation.setObjectName(_fromUtf8("imageTripleCorrelation"))
        self.imageTripleFittingCurve = QtGui.QLabel(self.tripleOutputTab)
        self.imageTripleFittingCurve.setGeometry(QtCore.QRect(670, 99, 281, 271))
        self.imageTripleFittingCurve.setFrameShape(QtGui.QFrame.Panel)
        self.imageTripleFittingCurve.setFrameShadow(QtGui.QFrame.Sunken)
        self.imageTripleFittingCurve.setText(_fromUtf8(""))
        self.imageTripleFittingCurve.setScaledContents(True)
        self.imageTripleFittingCurve.setObjectName(_fromUtf8("imageTripleFittingCurve"))
        self.frame = QtGui.QFrame(self.tripleOutputTab)
        self.frame.setGeometry(QtCore.QRect(340, 10, 281, 81))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.sampleResolutionLabel = QtGui.QLabel(self.frame)
        self.sampleResolutionLabel.setGeometry(QtCore.QRect(10, 10, 91, 41))
        self.sampleResolutionLabel.setWordWrap(True)
        self.sampleResolutionLabel.setObjectName(_fromUtf8("sampleResolutionLabel"))
        self.resolution32 = QtGui.QRadioButton(self.frame)
        self.resolution32.setGeometry(QtCore.QRect(100, 10, 82, 17))
        self.resolution32.setChecked(True)
        self.resolution32.setObjectName(_fromUtf8("resolution32"))
        self.resolution48 = QtGui.QRadioButton(self.frame)
        self.resolution48.setGeometry(QtCore.QRect(100, 30, 82, 17))
        self.resolution48.setObjectName(_fromUtf8("resolution48"))
        self.resolution64 = QtGui.QRadioButton(self.frame)
        self.resolution64.setGeometry(QtCore.QRect(100, 50, 82, 17))
        self.resolution64.setObjectName(_fromUtf8("resolution64"))
        self.tripleDeltasUsedCheckbox = QtGui.QCheckBox(self.tripleOutputTab)
        self.tripleDeltasUsedCheckbox.setEnabled(False)
        self.tripleDeltasUsedCheckbox.setGeometry(QtCore.QRect(670, 440, 131, 22))
        self.tripleDeltasUsedCheckbox.setChecked(False)
        self.tripleDeltasUsedCheckbox.setObjectName(_fromUtf8("tripleDeltasUsedCheckbox"))
        self.outputCorrelationTabWidget.addTab(self.tripleOutputTab, _fromUtf8(""))
        self.mainTabWidget.addTab(self.outputTab, _fromUtf8(""))
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(300, 630, 461, 23))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))

        self.retranslateUi(Dialog)
        self.mainTabWidget.setCurrentIndex(0)
        self.imageSettingsTabWidget.setCurrentIndex(0)
        self.correlationTabWidget.setCurrentIndex(0)
        self.outputCorrelationTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Image Correlation Spectroscopy", None))
        self.startButton.setText(_translate("Dialog", "START", None))
        self.stopButton.setText(_translate("Dialog", "STOP", None))
        self.batchModeButton.setText(_translate("Dialog", "SWITCH TO BATCH MODE", None))
        self.imageGroup.setTitle(_translate("Dialog", "Images", None))
        self.labelRGB.setText(_translate("Dialog", "All Channels", None))
        self.labelRed.setText(_translate("Dialog", "Red", None))
        self.labelGreen.setText(_translate("Dialog", "Green", None))
        self.labelBlue.setText(_translate("Dialog", "Blue", None))
        self.imageSettingsGroup.setTitle(_translate("Dialog", "Image Settings", None))
        self.loadImageRed.setText(_translate("Dialog", "Load Red Channel Image", None))
        self.loadImageGreen.setText(_translate("Dialog", "Load Green Channel Image", None))
        self.loadImageBlue.setText(_translate("Dialog", "Load Blue Channel Image", None))
        self.redChannelFile.setText(_translate("Dialog", "<no file>", None))
        self.greenChannelFile.setText(_translate("Dialog", "<no file>", None))
        self.blueChannelFile.setText(_translate("Dialog", "<no file>", None))
        self.imageSettingsTabWidget.setTabText(self.imageSettingsTabWidget.indexOf(self.loadThreeTab), _translate("Dialog", "Three Channel Images", None))
        self.loadImageRGB.setText(_translate("Dialog", "Load RGB Image", None))
        self.rgbFile.setText(_translate("Dialog", "<no file>", None))
        self.imageSettingsTabWidget.setTabText(self.imageSettingsTabWidget.indexOf(self.loadSingleTab), _translate("Dialog", "Single RGB Image", None))
        self.attributesGroup.setTitle(_translate("Dialog", "Image Attributes", None))
        self.imageSizeLabel.setText(_translate("Dialog", "Image Size:", None))
        self.avgIntensityLabel.setText(_translate("Dialog", "Average Intensity per Pixel:", None))
        self.redIntensityLabel.setText(_translate("Dialog", "Red - ", None))
        self.greenIntensityLabel.setText(_translate("Dialog", "Green - ", None))
        self.blueIntensityLabel.setText(_translate("Dialog", "Blue -", None))
        self.correlationSettingsGroup.setTitle(_translate("Dialog", "Correlation Settings", None))
        self.autoChannelsGroup.setTitle(_translate("Dialog", "Channels", None))
        self.redCheckbox.setText(_translate("Dialog", "Red", None))
        self.greenCheckbox.setText(_translate("Dialog", "Green", None))
        self.blueCheckbox.setText(_translate("Dialog", "Blue", None))
        self.autoGroup.setTitle(_translate("Dialog", "Auto-Correlation Parameters", None))
        self.autoRangeLabel.setText(_translate("Dialog", "Range:", None))
        self.autoG0Label.setText(_translate("Dialog", "g(0):", None))
        self.autoWLabel.setText(_translate("Dialog", "w:", None))
        self.autoGinfLabel.setText(_translate("Dialog", "gInf:", None))
        self.autoDeltasCheckbox.setText(_translate("Dialog", "Consider Deltas", None))
        self.correlationTabWidget.setTabText(self.correlationTabWidget.indexOf(self.autoCorrelationTab), _translate("Dialog", "Auto-Correlation", None))
        self.crossGroup.setTitle(_translate("Dialog", "Cross-Correlation Parameters", None))
        self.crossRangeLabel.setText(_translate("Dialog", "Range:", None))
        self.crossG0Label.setText(_translate("Dialog", "g(0):", None))
        self.crossWLabel.setText(_translate("Dialog", "w:", None))
        self.crossGinfLabel.setText(_translate("Dialog", "gInf:", None))
        self.crossChannelsGroup.setTitle(_translate("Dialog", "Channels", None))
        self.redGreenCheckbox.setText(_translate("Dialog", "Red-Green", None))
        self.redBlueCheckbox.setText(_translate("Dialog", "Red-Blue", None))
        self.greenBlueCheckbox.setText(_translate("Dialog", "Green-Blue", None))
        self.crossDeltasCheckbox.setText(_translate("Dialog", "Consider Deltas", None))
        self.correlationTabWidget.setTabText(self.correlationTabWidget.indexOf(self.crossCorrelationTab), _translate("Dialog", "Cross-Correlation", None))
        self.label.setText(_translate("Dialog", "Triple-correlation parameters are inputted sequentially. After loading image(s) into the program, press the START button to begin.", None))
        self.correlationTabWidget.setTabText(self.correlationTabWidget.indexOf(self.tripleCorrelationTab), _translate("Dialog", "Triple-Correlation", None))
        self.allAutoCrossGroup.setTitle(_translate("Dialog", "Auto/Cross Parameters", None))
        self.allAutoCrossRangeLabel.setText(_translate("Dialog", "Range:", None))
        self.allAutoCrossG0Label.setText(_translate("Dialog", "g(0):", None))
        self.allAutoCrossWLabel.setText(_translate("Dialog", "w:", None))
        self.allAutoCrossGinfLabel.setText(_translate("Dialog", "gInf:", None))
        self.allDeltasCheckbox.setText(_translate("Dialog", "Consider Deltas", None))
        self.correlationTabWidget.setTabText(self.correlationTabWidget.indexOf(self.allCorrelationsTab), _translate("Dialog", "All", None))
        self.messageBox.setText(_translate("Dialog", "Ready.", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.inputTab), _translate("Dialog", "Input Parameters", None))
        self.labelOutputRed.setText(_translate("Dialog", "Red", None))
        self.labelOutputGreen.setText(_translate("Dialog", "Green", None))
        self.labelOutputBlue.setText(_translate("Dialog", "Blue", None))
        self.labelAutoResNorm.setText(_translate("Dialog", "Res. Norm.", None))
        self.labelAutoG0.setText(_translate("Dialog", "g(0)", None))
        self.labelAutoW.setText(_translate("Dialog", "w", None))
        self.labelAutoGinf.setText(_translate("Dialog", "gInf", None))
        self.autoDeltasUsedCheckbox.setText(_translate("Dialog", "Deltas Used", None))
        self.outputCorrelationTabWidget.setTabText(self.outputCorrelationTabWidget.indexOf(self.autoOutputTab), _translate("Dialog", "Auto-Correlation", None))
        self.labelOutputRB.setText(_translate("Dialog", "Red-Blue", None))
        self.labelOutputRG.setText(_translate("Dialog", "Red-Green", None))
        self.labelOutputGB.setText(_translate("Dialog", "Green-Blue", None))
        self.labelCrossResNorm.setText(_translate("Dialog", "Res. Norm.", None))
        self.labelCrossG0.setText(_translate("Dialog", "g(0)", None))
        self.labelCrossW.setText(_translate("Dialog", "w", None))
        self.labelCrossGinf.setText(_translate("Dialog", "gInf", None))
        self.crossDeltasUsedCheckbox.setText(_translate("Dialog", "Deltas Used", None))
        self.outputCorrelationTabWidget.setTabText(self.outputCorrelationTabWidget.indexOf(self.crossOutputTab), _translate("Dialog", "Cross-Correlation", None))
        self.labelOutputTripleFourier.setText(_translate("Dialog", "Fourier Transform (Red) Surface Plot", None))
        self.labelOutputTripleCorrelation3D.setText(_translate("Dialog", "Triple-Correlation Surface Plot", None))
        self.labelOutputTripleCorrelation.setText(_translate("Dialog", "Fitting Curve", None))
        self.labelTripleResNorm.setText(_translate("Dialog", "Res. Norm.", None))
        self.tripleG0.setText(_translate("Dialog", "g(0):", None))
        self.tripleW.setText(_translate("Dialog", "w:", None))
        self.tripleRange.setText(_translate("Dialog", "Range:", None))
        self.tripleGinf.setText(_translate("Dialog", "ginf:", None))
        self.sampleResolutionLabel.setText(_translate("Dialog", "Sample Resolution:", None))
        self.resolution32.setText(_translate("Dialog", "32 x 32", None))
        self.resolution48.setText(_translate("Dialog", "48 x 48", None))
        self.resolution64.setText(_translate("Dialog", "64 x 64", None))
        self.tripleDeltasUsedCheckbox.setText(_translate("Dialog", "Deltas Used", None))
        self.outputCorrelationTabWidget.setTabText(self.outputCorrelationTabWidget.indexOf(self.tripleOutputTab), _translate("Dialog", "Triple-Correlation", None))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.outputTab), _translate("Dialog", "Output", None))

